(function(g){var window=this;'use strict';var $op=function(l,y,r){g.Z(function(c){l.G=g.Gd(y,r);g.Kl(c)})},fE=function(l){l.isActive()||l.start()},BAH=function(l,y){return y?l.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},txz=function(l){return g.O8(l)||l.j("web_enable_caption_language_preference_stickiness")},DoB=function(l,y){var r=new g.Ir;
r.languageCode=l.languageCode;r.languageName=l.languageName;r.name=l.name;r.displayName=l.displayName;r.kind=l.kind;r.isDefault=!1;r.G=l.G;r.isTranslateable=l.isTranslateable;r.vssId=l.vssId;r.url=l.url;r.translationLanguage=y;l.xtags&&(r.xtags=l.xtags);l.captionId&&(r.captionId=l.captionId);return r},doj=function(l,y){var r,c,O;
return g.Z(function(H){if(H.G==1)return r=l+"|"+y,g.h(H,g.Oo(),2);if(H.G!=3){c=H.K;if(!c)throw g.vj("gct");return g.h(H,g.Xl(c),3)}O=H.K;return H.return(O.get("captions",r))})},iHg=function(l,y,r){doj(l,y).then(function(c){c&&r(c.trackData,new g.Ir(c.metadata))})},w5J=function(l){if(!X5Q.test(l))throw Error("'"+l+"' is not a valid hex color");
l.length==4&&(l=l.replace(QPJ,"#$1$1$2$2$3$3"));l=l.toLowerCase();l=parseInt(l.slice(1),16);return[l>>16,l>>8&255,l&255]},Pkg=function(){var l=void 0;
l=l===void 0?{}:l;var y="suggest_correction"in g.g9g?g.g9g.suggest_correction:"Edit caption";y=y||"";var r={},c;for(c in l){r={CH:r.CH};r.CH=c;var O=function(H){return function(){return String(l[H.CH])}}(r);
y=y.replace(new RegExp("\\$\\{"+r.CH+"\\}","gi"),O);y=y.replace(new RegExp("\\$"+r.CH,"gi"),O)}return y},xoJ=function(){return g.QD("yt-player-caption-display-settings")},Ns=function(){this.segments=[]},epx=function(l,y){var r=g.CM(l.segments,y);
r>=0||r<0&&(-r-1)%2===1||(r=-r-1,r>0&&y-l.segments[r-1]===1&&r<l.segments.length&&l.segments[r]-y===1?(g.kB(l.segments,r),g.kB(l.segments,r-1)):r>0&&y-l.segments[r-1]===1?l.segments[r-1]=y:r<l.segments.length&&l.segments[r]-y===1?l.segments[r]=y:(g.HI(l.segments,r,0,y),g.HI(l.segments,r+1,0,y)))},nTI=function(l,y,r,c,O,H){g.X.call(this);
this.policy=l;this.player=y;this.Kq=r;this.W=c;this.C=O;this.X=H;this.B=new Ns;this.L=-1;this.N=this.K=this.G=null;this.i8=0;this.J=new g.yU(this.WK,1E3,this);this.events=new g.n4(this);g.Q(this,this.J);g.Q(this,this.events);this.events.S(y,"SEEK_COMPLETE",this.AY);this.AY();this.WK()},bHg=function(l){return l.G&&l.G.L?l.G.L+l.player.lT()<l.player.getCurrentTime():!1},RpH=function(l,y){if(l.policy.jV&&l.player.XL()){var r=g.k2(y,l.policy,{});
r.set("pot",l.player.XL());r=r.IF()}else r=g.k2(y,l.policy,{}).IF();var c={format:"RAW",withCredentials:!0};if(l.policy.II){c.method="POST";var O=y.B;O&&Object.keys(O).length>0?c.postBody=g.OX(O,g.VH):c.postBody=(0,g.vQ)([120,0])}l.C&&(c.responseType="arraybuffer");var H=++l.i8,V=(0,g.$$)();l.N=g.th(r,c,3,100).then(function(T){if(l.policy.Lz&&H%100===1){var f=(0,g.$$)();l.player.AC("caprsp",{rn:H,ms:f-V,kb:(T.xhr.responseText.length/1024).toFixed()})}a:{T=T.xhr;l.Lq();if(l.K){var N=!(l.C?T.response:
T.responseText)||T.status>=400;if(f=g.JfZ(T)){T=g.k2(l.K,l.policy,{});l.K.I2(T,f);RpH(l,l.K);break a}N?l.player.AC("capfail",{status:T.status}):(l.player.K4().Mt("fcb_r"),f=l.K.mR[0].jj,l.W!=null&&l.L!==f&&(N=l.K.mR[0],l.C?l.W(T.response,(N.startTime+l.player.lT())*1E3):l.W(T.responseText,(N.startTime+l.player.lT())*1E3),l.L=f))}l.K=null;l.N=null}}).v_(function(T){l.K=null;
l.N=null;var f;l.player.AC("capfail",{rn:H,status:(f=T.xhr)==null?void 0:f.status})});
l.K=y;epx(l.B,l.K.mR[0].jj)},SS=function(l,y){g.q3.call(this,y);
this.G=l;this.V=y;this.N=null;this.L=!1;this.logger=new g.NG("caps");this.J=g.BK(this.V.D())&&!this.G.isManifestless},zpg=function(l,y){var r=[],c;
for(c in l.G.G)if(l.G.G.hasOwnProperty(c)){var O=l.G.G[c];if(g.Wy(O,y||null)){var H=O.info.id,V=H,T="."+H,f="",N="";if(O=O.info.captionTrack)H=O.languageCode,V=O.displayName,T=O.vssId,f=O.kind,N=O.id;else{O=H;var S=g.BcJ.get(O);S==null&&(S=Uob[O]||Uob[O.replace(/-/g,"_")],g.BcJ.set(O,S));O=S;V=O||V}r.push(new g.Ir({id:c,languageCode:H,languageName:V,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:T,kind:f,captionId:N}))}}return r},kRJ=function(l,y){return y!=null&&y in l.G.G?l.G.G[y]:null},
jPg=function(l,y,r){var c=[],O;
for(O in l.G.G)if(l.G.G.hasOwnProperty(O)){var H=l.G.G[O];if(g.Wy(H,r||null)){var V=H.info.captionTrack;V&&V.languageCode===y&&c.push(H)}}return c.length?c[0]:null},FM=function(l,y,r,c,O,H,V,T,f,N){var S=N.isInline()&&!0,F={};
Object.assign(F,y);Object.assign(F,l.params);Object.assign(F,r);var p={};Object.assign(p,y.wX);l.params.wX&&Object.assign(p,l.params.wX);Object.assign(p,r.wX);S&&(F.windowOpacity=.6,p.backgroundOpacity=0);F.wX=p;var E=F.z0===1,u=[{U:"span",Z:"captions-text",Y:{style:"word-wrap: normal; display: block;"}}],I,q,W;(T=T.aI("caption_edit_on_hover")&&((I=N.getVideoData().getPlayerResponse())==null?void 0:(q=I.captions)==null?void 0:(W=q.playerCaptionsTracklistRenderer)==null?void 0:W.openTranscriptCommand))&&
u.unshift({U:"button",Z:"caption-edit",Y:{tabindex:"0","aria-label":Pkg()},T:[{U:"svg",Y:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},T:[{U:"path",Y:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.n.call(this,{U:"div",Z:"caption-window",Y:{id:"caption-window-"+l.id,dir:E?"rtl":"ltr",tabindex:"0",lang:F.lang},T:u});var v=
this;this.J=[];this.Mf=!1;this.K=l;this.Cq=this.II=null;this.playerWidth=H;this.playerHeight=V;this.W=null;this.maxWidth=H*.96;this.maxHeight=V*.96;this.G=F;this.tD=r;this.i8=y;this.B=this.BT("captions-text");this.f$=this.B.style.getPropertyValue("box-decoration-break")!==""||this.B.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.ZZ=LgI(c,O,H,V);this.Hg=f;T&&(this.L=this.BT("caption-edit"),this.S(this.L,"click",function(){v.Hg()}));
this.type=0;this.Qr=this.ZZ*lnp(p);this.cg=S;l=new g.R2(this.element,!0);g.Q(this,l);l.subscribe("dragstart",this.Pa,this);l.subscribe("dragmove",this.Yd,this);l.subscribe("dragend",this.lE,this);this.Y7=this.vT=this.w9=this.l8=0;l="";this.G.windowOpacity&&(l=w5J(this.G.windowColor),l="rgba("+l[0]+","+l[1]+","+l[2]+","+this.G.windowOpacity+")");y={"background-color":l,display:this.G.isVisible===!1?"none":"","text-align":yZQ[this.G.textAlign]};this.f$&&(y["border-radius"]=l?this.Qr/8+"px":"");(this.N=
this.K.params.z0===2||this.K.params.z0===3)&&rZQ(this,this.element);g.ET(this.element,y);if(S){var G;(G=this.element.parentElement)==null||G.style.setProperty("--caption-window-color",l)}switch(this.G.Cb){case 0:case 1:case 2:g.Nr(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Nr(this.element,"ytp-caption-window-bottom")}},rZQ=function(l,y){var r="vertical-rl";
l.G.bP===1&&(r="vertical-lr");g.sr&&(r=r==="vertical-lr"?"tb-lr":"tb-rl");g.ET(y,"-o-writing-mode",r);g.ET(y,"-webkit-writing-mode",r);g.ET(y,"writing-mode",r);g.ET(y,"text-orientation","upright");g.Nr(y,"ytp-vertical-caption");l.K.params.z0===3&&(g.ET(y,"text-orientation",""),g.ET(y,"transform","rotate(180deg)"))},lnp=function(l){var y=1+.25*(l.fontSizeIncrement||0);
if(l.offset===0||l.offset===2)y*=.8;return y},cZJ=function(l,y){var r={},c=y.background?y.background:l.G.wX.background;
if(y.backgroundOpacity!=null||y.background){var O=y.backgroundOpacity!=null?y.backgroundOpacity:l.G.wX.backgroundOpacity;c=w5J(c);r.background="rgba("+c[0]+","+c[1]+","+c[2]+","+O+")";l.f$&&(r["box-decoration-break"]="clone",r["border-radius"]=l.Qr/8+"px")}if(y.fontSizeIncrement!=null||y.offset!=null)r["font-size"]=l.ZZ*lnp(y)+"px";c=1;O=y.color||l.G.wX.color;if(y.color||y.textOpacity!=null)O=w5J(O),c=y.textOpacity==null?l.G.wX.textOpacity:y.textOpacity,O="rgba("+O[0]+","+O[1]+","+O[2]+","+c+")",
r.color=O,r.fill=O;var H=y.charEdgeStyle;H===0&&(H=void 0);if(H){O="rgba(34, 34, 34, "+c+")";var V="rgba(204, 204, 204, "+c+")";y.nm&&(V=O=y.nm);var T=l.ZZ/16/2,f=Math.max(T,1),N=Math.max(2*T,1),S=Math.max(3*T,1),F=Math.max(5*T,1);c=[];switch(H){case 4:for(;S<=F;S+=T)c.push(N+"px "+N+"px "+S+"px "+O);break;case 1:N=window.devicePixelRatio>=2?.5:1;for(H=f;H<=S;H+=N)c.push(H+"px "+H+"px "+O);break;case 2:c.push(f+"px "+f+"px "+V);c.push("-"+f+"px -"+f+"px "+O);break;case 3:for(S=0;S<5;S++)c.push("0 0 "+
N+"px "+O)}r["text-shadow"]=c.join(", ")}O="";switch(y.fontFamily){case 1:O='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:O='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:O='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:O='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:O='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:O=g.zd()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:O='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}O&&(r["font-family"]=O);O=y.offset;O==null&&(O=l.G.wX.offset);switch(O){case 0:r["vertical-align"]="sub";break;case 2:r["vertical-align"]="super"}y.fontFamily===7&&(r["font-variant"]="small-caps");y.bold&&(r["font-weight"]="bold");y.italic&&(r["font-style"]="italic");y.underline&&(r["text-decoration"]=
"underline");y.Hqw&&(r.visibility="hidden");y.zQ===1&&l.N&&(r["text-combine-upright"]="all",r["text-orientation"]="mixed",O=g.CS||g.Wj,l.K.params.z0===3?r.transform=O?"rotate(90deg)":"rotate(180deg)":O&&(r.transform="rotate(-90deg)"));if(y.textEmphasis===1||y.textEmphasis===2||y.textEmphasis===3||y.textEmphasis===4||y.textEmphasis===5)if(g.CS)r["font-weight"]="bold";else switch(r["text-emphasis-style"]="filled circle",r["text-emphasis-color"]="currentcolor",r["webkit-text-emphasis"]="filled circle",
y.textEmphasis){case 4:case 3:r["text-emphasis-position"]="under left";r["webkit-text-emphasis-position"]="under left";break;case 5:case 2:r["text-emphasis-position"]="over right",r["webkit-text-emphasis-position"]="over right"}return r},pE=function(l){l=l.split("px");
return l.length>0?(l=Number(l[0]))?l:0:0},OgB=function(l){l.W=g.rC("SPAN");
g.ET(l.W,{display:"block"});g.Nr(l.W,"caption-visual-line");l.B.appendChild(l.W)},Hgx=function(l,y){var r=g.rC("SPAN");
g.ET(r,{display:"inline-block","white-space":"pre-wrap"});g.ET(r,cZJ(l,y));r.classList.add("ytp-caption-segment");l.W.appendChild(r);r.previousElementSibling&&(g.ET(r.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ET(r,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return r},V4b=function(l,y,r){l.Mf=l.Mf||!!r;
var c={};Object.assign(c,l.G.wX);Object.assign(c,r||y.G);Object.assign(c,l.tD.wX);(r=!l.W)&&OgB(l);for(var O=l.II&&l.Cq&&g.$T(c,l.Cq)?l.II:Hgx(l,c),H=typeof y.text==="string",V=H?y.text.split("\n"):[y.text],T=0;T<V.length;T++){var f=T>0||!y.append,N=V[T];f&&!r?(OgB(l),O=Hgx(l,c)):f&&r&&(r=!1);N&&(O.appendChild(H?g.c7(N):N),H||N.tagName!=="RUBY"||N.childElementCount!==4||g.CS||!g.M0(N.children[2],"text-emphasis")||(f=l.N?"padding-right":"padding-top",g.M0(N.children[2],"text-emphasis-position")&&(f=
l.N?"padding-left":"padding-bottom"),g.jx?g.ET(O,f,"1em"):g.ET(O,f,"0.5em")))}l.Cq=c;l.II=O;l.J.push(y)},LgI=function(l,y,r,c){var O=y/360*16;
y>=l&&(l=640,c>r*1.3&&(l=480),O=r/l*16);return O},g_Q=function(){this.N=this.time=this.mode=this.K=0;
this.B=new Ctz(this);this.C=new Ctz(this);this.G=[];this.clear()},fnz=function(l,y,r){if(l===255&&y===255||!l&&!y)return{JI:l,
Wi:y,result:0};l=TCs[l];y=TCs[y];if(l&128){var c;if(c=!(y&128))c=y,c=r.eO()&&r.Wi===c;if(c)return{JI:l,Wi:y,result:1}}else if(y&128&&1<=l&&l<=31)return{JI:l,Wi:y,result:2};return{JI:l,Wi:y,result:3}},SeJ=function(l,y,r,c){y===255&&r===255||!y&&!r?(++l.N===45&&l.reset(),l.B.K.clear(),l.C.K.clear()):(l.N=0,NCp(l.B,y,r,c))},FLH=function(l,y){l.G.sort(function(O,H){var V=O.time-H.time;
return V===0?O.order-H.order:V});
for(var r=g.a(l.G),c=r.next();!c.done;c=r.next())c=c.value,l.time=c.time,c.type===0?SeJ(l,c.ZF,c.SR,y):c.type===1&&l.K&496&&NCp(l.C,c.ZF,c.SR,y);l.G.length=0},Eu=function(){this.type=0},u0=function(){this.state=this.Wi=this.JI=0},p7B=function(){this.timestamp=this.G=0},Ms=function(l){this.C=l;
this.N=[];this.G=this.K=this.row=0;this.style=new Eu;for(l=this.B=0;l<=15;l++){this.N[l]=[];for(var y=0;y<=32;y++)this.N[l][y]=new p7B}},aD=function(l,y){if(l.style.type===3){for(var r=0,c=0,O=l.C.time+0,H="",V="",T=O,f=1;f<=15;++f){for(var N=!1,S=c?c:1;S<=32;++S){var F=l.N[f][S];
if(F.G!==0){r===0&&(r=f,c=S);N=String.fromCharCode(F.G);var p=F.timestamp;p<O&&(O=p);F.timestamp=T;V&&(H+=V,V="");H+=N;N=!0}if((F.G===0||S===32)&&N){V="\n";break}else if(c&&!N)break}if(r&&!N)break}H&&y.B(r,c,O,T,H)}else for(c=r=0,H=O=l.C.time+0,V=1;V<=15;++V)for(T="",f=1;f<=32;++f)if(S=l.N[V][f],F=S.G,F!==0&&(r===0&&(r=V,c=f),N=String.fromCharCode(F),p=S.timestamp,p<=O&&(O=p),T+=N,S.reset()),f===32||F===0)T&&y.B(r,c,O,H,T),O=H,T="",c=r=0},s8s=function(l,y){switch(l){case 0:return E_H[(y&127)-32];
case 1:return uLB[y&15];case 2:return M4J[y&31];case 3:return anb[y&31]}return 0},KE=function(l){return l.N[l.row][l.K]},ID=function(l,y,r){y>=2&&l.K>1&&(--l.K,KE(l).G=0);
var c=KE(l);c.timestamp=l.C.time+0;c.G=s8s(y,r);l.K<32&&l.K++},KLx=function(l,y,r,c){for(var O=0;O<c;O++)for(var H=0;H<=32;H++){var V=l.N[y+O][H],T=l.N[r+O][H];
V.G=T.G;V.timestamp=T.timestamp}},YA=function(l,y,r){for(var c=0;c<r;c++)for(var O=0;O<=32;O++)l.N[y+c][O].reset()},Ing=function(l){l.row=l.G>0?l.G:1;
l.K=1;YA(l,0,15)},Yeg=function(l){this.N=l;
this.C=0;this.style=new Eu;this.L=new Ms(this.N);this.J=new Ms(this.N);this.text=new Ms(this.N);this.K=this.L;this.B=this.J;this.G=this.K},qeb=function(l,y,r){var c=l.K,O=!1;
switch(l.style.get()){case 4:case 1:case 2:l.style.get()===4&&c.G>0||(aD(c,r),Ing(l.K),Ing(l.B),c.row=15,c.G=y,O=!0)}l.style.set(3);l.G=c;l.G.style=l.style;l.N.mode=1<<c.B;O?c.K=1:c.G!==y&&(c.G>y?(aD(c,r),YA(c,c.row-c.G,y)):c.row<y&&(y=c.G),c.G=y)},AZx=function(l){l.style.set(1);
l.G=l.B;l.G.G=0;l.G.style=l.style;l.N.mode=1<<l.G.B},WLs=function(l){l.style.set(4);
l.G=l.text;l.G.style=l.style;l.N.mode=1<<l.G.B},Ctz=function(l){this.G=l;
this.C=0;this.N=new Yeg(this.G);this.L=new Yeg(this.G);this.K=new u0;this.B=this.N},NCp=function(l,y,r,c){l.K.update();
y=fnz(y,r,l.K);switch(y.result){case 0:return;case 1:case 2:return}var O=y.JI;r=y.Wi;if(32<=O||!O)l.G.mode&l.G.K&&(y=O,y&128&&(y=127),r&128&&(r=127),l=l.B.G,y&96&&ID(l,0,y),r&96&&ID(l,0,r),y!==0&&r!==0&&l.style.type===3&&aD(l,c));else if(O&16)a:if(!l.K.matches(O,r)&&(y=l.K,y.JI=O,y.Wi=r,y.state=2,y=O&8?l.L:l.N,l.B=y,l.G.mode=1<<(l.C<<2)+(y.C<<1)+(y.style.type===4?1:0),(l.G.mode|1<<(l.C<<2)+(y.C<<1)+(y.style.type!==4?1:0))&l.G.K))if(r&64){c=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(O&7)<<1|r>>5&1];
l=r&16?((r&14)>>1)*4:0;r=y.G;switch(y.style.get()){case 4:c=r.row;break;case 3:if(c!==r.row){if(c<r.G&&(c=r.G,c===r.row))break;var H=1+r.row-r.G,V=1+c-r.G;KLx(r,V,H,r.G);y=H;O=r.G;V<H?(H=V+O-H,H>0&&(y+=H,O-=H)):(H=H+O-V,H>0&&(O-=H));YA(r,y,O)}}r.row=c;r.K=l+1}else switch(O&7){case 1:switch(r&112){case 32:ID(y.G,0,32);break a;case 48:r===57?(c=y.G,KE(c).G=0,c.K<32&&c.K++):ID(y.G,1,r&15)}break;case 2:r&32&&ID(y.G,2,r&31);break;case 3:r&32&&ID(y.G,3,r&31);break;case 4:case 5:if(32<=r&&r<=47)switch(r){case 32:AZx(y);
break;case 33:c=y.G;c.K>1&&(--c.K,KE(c).G=0);break;case 36:c=y.G;y=KE(c);for(l=0;l<=15;l++)for(r=0;r<=32;r++)if(c.N[l][r]===y){for(;r<=32;r++)c.N[l][r].reset();break}break;case 37:qeb(y,2,c);break;case 38:qeb(y,3,c);break;case 39:qeb(y,4,c);break;case 40:ID(y.G,0,32);break;case 41:y.style.set(2);y.G=y.K;y.G.G=0;y.G.style=y.style;y.N.mode=1<<y.G.B;break;case 42:c=y.text;c.G=15;c.style.set(4);Ing(c);WLs(y);break;case 43:WLs(y);break;case 44:l=y.K;switch(y.style.get()){case 1:case 2:case 3:aD(l,c)}YA(l,
0,15);break;case 45:b:{l=y.G;switch(y.style.get()){default:case 2:case 1:break b;case 4:if(l.row<15){++l.row;l.K=1;break b}break;case 3:}l.G<2&&(l.G=2,l.row<l.G&&(l.row=l.G));y=l.row-l.G+1;aD(l,c);KLx(l,y,y+1,l.G-1);YA(l,l.row,1)}break;case 46:YA(y.B,0,15);break;case 47:aD(y.K,c),y.B.updateTime(y.N.time+0),c=y.B,y.B=y.K,y.K=c,AZx(y)}break;case 7:switch(r){case 33:case 34:case 35:c=y.G,(c.K+=r&3)>32&&(c.K=32)}}},mzj=function(){},qs=function(l,y,r,c,O,H,V){H=H===void 0?!1:H;
V=V===void 0?null:V;g.F8.call(this,l,l+y,{priority:r,namespace:"captions"});this.windowId=c;this.text=O;this.append=H;this.G=V},JZs=function(l,y,r,c,O,H,V){var T=H[0],f=V[T.getAttribute("p")];
if(f.EZ===1){var N=H[1],S=H[2];H=H[3];T.getAttribute("t");N.getAttribute("t");S.getAttribute("t");H.getAttribute("t");T.getAttribute("p");N.getAttribute("p");H.getAttribute("p");V=V[S.getAttribute("p")];T=v_J(T.textContent,N.textContent,S.textContent,H.textContent,V);return new qs(l,y,O,r,T,c,f)}switch(f.EZ){case 9:case 10:f.textEmphasis=1;break;case 11:f.textEmphasis=2;break;case 12:f.textEmphasis=3;break;case 13:f.textEmphasis=4;break;case 14:f.textEmphasis=5}return new qs(l,y,O,r,T.textContent||
"",c,f)},v_J=function(l,y,r,c,O){var H=g.zd(),V=H?g.rC("DIV"):g.rC("RUBY"),T=g.rC("SPAN");
T.textContent=l;V.appendChild(T);l=H?g.rC("DIV"):g.rC("RP");l.textContent=y;V.appendChild(l);y=H?g.rC("DIV"):g.rC("RT");y.textContent=r;V.appendChild(y);r=O.EZ;if(r===10||r===11||r===12||r===13||r===14)if(g.ET(y,"text-emphasis-style","filled circle"),g.ET(y,"text-emphasis-color","currentcolor"),g.ET(y,"webkit-text-emphasis","filled circle"),O.EZ===11||O.EZ===13)g.ET(y,"webkit-text-emphasis-position","under left"),g.ET(y,"text-emphasis-position","under left");r=!0;if(O.EZ===4||O.EZ===7||O.EZ===12||
O.EZ===14)g.ET(V,"ruby-position","over"),g.ET(V,"-webkit-ruby-position","before");else if(O.EZ===5||O.EZ===6||O.EZ===11||O.EZ===13)g.ET(V,"ruby-position","under"),g.ET(V,"-webkit-ruby-position","after"),r=!1;O=H?g.rC("DIV"):g.rC("RP");O.textContent=c;V.appendChild(O);H&&(c=r,g.ET(V,{display:"inline-block",position:"relative"}),H=V.firstElementChild.nextElementSibling,g.ET(H,"display","none"),H=H.nextElementSibling,g.ET(H,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ET(V.lastElementChild,"display","none"),c?(g.ET(V,"padding-top","0.6em"),g.ET(H,"top","0")):(g.ET(V,"padding-bottom","0.6em"),g.ET(H,"bottom","0")));return V},AR=function(){g.X.apply(this,arguments)},W8=function(l,y,r,c,O){g.F8.call(this,l,l+y,{priority:r,
namespace:"captions"});this.id=c;this.params=O;this.G=[]},o_Q=function(l){var y="_"+mr++;
return new W8(0,0x8000000000000,0,y,l)},v8=function(l){AR.call(this);
this.N=l;this.pens={};this.J={};this.W={};this.B="_"+mr++;this.L={};this.K=this.G=null;this.C=!0},JR=function(l,y){l=l.getAttribute(y);
if(l!=null)return Number(l)},oD=function(l,y){l=l.getAttribute(y);
if(l!=null)return l==="1"},hR=function(l,y){l=JR(l,y);
return l!==void 0?l:null},Z2=function(l,y){l=l.getAttribute(y);
if(l!=null)return Gq.test(l),l},hUb=function(l,y){var r={},c=y.getAttribute("ws");
Object.assign(r,c?l.W[c]:l.N);l=hR(y,"mh");l!=null&&(r.zo=l);l=hR(y,"ju");l!=null&&(r.textAlign=l);l=hR(y,"pd");l!=null&&(r.z0=l);l=hR(y,"sd");l!=null&&(r.bP=l);l=Z2(y,"wfc");l!=null&&(r.windowColor=l);y=JR(y,"wfo");y!==void 0&&(r.windowOpacity=y/255);return r},GoJ=function(l,y){var r={},c=y.getAttribute("wp");
c&&Object.assign(r,l.J[c]);l=hR(y,"ap");l!=null&&(r.Cb=l);l=JR(y,"cc");l!=null&&(r.Da=l);l=JR(y,"ah");l!=null&&(r.e9=l);l=JR(y,"rc");l!=null&&(r.XA=l);y=JR(y,"av");y!=null&&(r.g7=y);return r},ZgJ=function(l,y,r,c){var O={};
Object.assign(O,GoJ(l,y));Object.assign(O,hUb(l,y));c?g.$T(O,l.N)?(c=l.B,O=l.N):c="_"+mr++:c=y.getAttribute("id")||"_"+mr++;l=JR(y,"t")+r;y=JR(y,"d")||0x8000000000000;if(O.z0===2||O.z0===3)r=O.XA,O.XA=O.Da,O.Da=r;return new W8(l,y,0,c,O)},$A=function(l){AR.call(this);
this.C=l;this.G=new Map;this.N=new Map;this.B=new Map;this.K=new Map},B8=function(l){l=g.Sx(Math.round(l),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-l.length)+l},$zB=function(l,y,r,c,O){c===0&&(c=0x8000000000000);
var H={};y.wpWinPosId&&Object.assign(H,l.N.get(y.wpWinPosId));y.wsWinStyleId&&Object.assign(H,l.B.get(y.wsWinStyleId));l=y.rcRowCount;l!==void 0&&(H.XA=l);y=y.ccColCount;y!==void 0&&(H.Da=y);if(H.z0===2||H.z0===3)y=H.XA,H.XA=H.Da,H.Da=y;return new W8(r,c,0,O,H)},tR=function(l,y,r){g.q3.call(this,l);
this.videoData=y;this.audioTrack=r;this.C=y.U2},D2=function(l,y,r,c,O,H,V,T,f,N){FM.call(this,l,y,r,c,O,H,V,T,f,N);
this.type=1},dL=function(l,y,r){this.trackData=l;
this.L=r;this.version=this.C=this.N=this.byteOffset=0;this.K=[];this.G=new DataView(this.trackData)},i0=function(l){var y=l.byteOffset;
l.byteOffset+=1;return l.G.getUint8(y)},XM=function(l){var y=l.byteOffset;
l.byteOffset+=4;return l.G.getUint32(y)},QZ=function(l,y){AR.call(this);
this.K=l;this.N=y;this.track=this.N.languageName==="CC3"?4:0;this.G=new g_Q;this.G.K=1<<this.track},t4J=function(l){if(typeof l==="string")return!1;
l=new dL(l,8,0);return BCJ(l)},BCJ=function(l){if(!(l.byteOffset<l.G.byteLength)||XM(l)!==1380139777)return!1;
l.version=i0(l);if(l.version>1)return!1;i0(l);i0(l);i0(l);return!0},wL=function(l,y,r,c,O,H,V,T,f,N){FM.call(this,l,y,r,c,O,H,V,T,f,N);
var S=this;this.type=2;this.Nf=[];this.Kq=this.X=this.r9=0;this.Uz=NaN;this.ez=0;this.xN=null;this.qf=new g.yU(this.cj,433,this);this.Sj=!1;this.L&&(N.createClientVe(this.L,this,167342),this.S(this.L,"click",function(){N.logClick(S.L)}),l=new g.R2(this.element,!0),g.Q(this,l),l.subscribe("hoverstart",function(){N.logVisibility(S.L,!0)},this));
g.Nr(this.element,"ytp-caption-window-rollup");g.Q(this,this.qf);this.Sj=T.aI("html5_rollup_caption_window_enable_transition_end_listener");g.ET(this.element,"overflow","hidden")},DzJ=function(l,y){if(!y)return"";
l.N&&l.K.params.bP!==1&&(y*=-1);return"translate"+(l.N?"X":"Y")+"("+y+"px)"},dzg=function(l){l.Nf=Array.from(l.element.getElementsByClassName("caption-visual-line"));
for(var y=l.K.params.XA,r=0,c=0,O=l.Nf.length-1;r<y&&O>-1;){var H=l.Nf[O];c+=l.N?H.offsetWidth:H.offsetHeight;r++;O--}l.X=c;y=Math;r=y.max;isNaN(l.Uz)&&((c=l.G.Da)?(O=g.rC("SPAN"),g.To(O,"\u2013".repeat(c)),g.ET(O,cZJ(l,l.G.wX)),l.B.appendChild(O),l.Uz=O.offsetWidth,l.B.removeChild(O)):l.Uz=0);c=l.B;l.Kq=r.call(y,l.Uz,l.ez,(l.N?c.offsetHeight:c.offsetWidth)+1)},igp=function(l,y){dzg(l);
var r=l.Nf.reduce(function(H,V){return(l.N?V.offsetWidth:V.offsetHeight)+H},0);
r=l.X-r;if(r!==l.r9){var c=r>0&&l.r9===0,O=r<l.r9;y||isNaN(r)||c||!O||(g.Nr(l.element,"ytp-rollup-mode"),l.Sj?l.S(l.element,"transitionend",l.cj):g.rD(l.qf));g.ET(l.B,"transform",DzJ(l,r));l.r9=r}dzg(l)},X7J=function(l,y,r,c){var O=this;
this.V=l;this.N=y;this.logger=r;this.Ve=c;this.FD=[];this.X9=[];this.G=null;this.GT={Ilr:function(){return O.G},
T$:function(){return O.FD}};
l=g.Ib(this.V.D().experiments,"html5_override_micro_discontinuities_threshold_ms");this.K=l>0?l:10},PtJ=function(l,y){l.G=function(r,c){if(r.info.C){var O=r;
if(l.X9.length>0){for(O=l.X9.shift();l.X9.length>0;)O=g.gm(O,l.X9.shift());O=g.gm(O,r)}if(O){r=O;try{var H=g.TQ(r)*1E3}catch(N){H=r.info.startTime*1E3}try{var V=g.als(r)*1E3}catch(N){V=r.info.duration*1E3}if(H<0||V<0)H<0&&(H=r.info.startTime*1E3),V<0&&(V=r.info.duration*1E3);r.info.startTime=H/1E3;r.info.B=H/1E3;r.info.duration=V/1E3;r.info.W=V/1E3;H=l.QZ(O);V=H.jj;H={formatId:H.formatId,startTimeMs:H.startTimeMs,durationMs:H.durationMs,w5:V,vt:V};V=Q8j(l.FD,H.startTimeMs);var T=(r=V>=0?l.FD[V]:null)?
r.startTimeMs+r.durationMs:0,f=H.startTimeMs+H.durationMs;!r||H.startTimeMs-T>l.K?l.FD.splice(V+1,0,H):(r.durationMs=Math.max(T,f)-r.startTimeMs,r.vt=Math.max(r.vt,H.vt));c(l.FD);c=O.Nc();w7s(l.N,c.buffer.slice(c.byteOffset,c.byteLength+c.byteOffset),y,O.info.B)}else l.logger.G(350058965,"Empty slice")}else l.X9.push(r)};
l.V.addEventListener("sabrCaptionsDataLoaded",l.G)},Q8j=function(l,y){l=g.CM(l,{startTimeMs:y},function(r,c){return r.startTimeMs-c.startTimeMs});
return l>=0?l:-l-2},xzs=function(l,y){g.q3.call(this,y);
this.G=l;this.V=y;this.logger=new g.NG("caps");this.N=this.L=null;this.J=new X7J(this.V,this,this.logger,this.G.Ve)},w7s=function(l,y,r,c){l.logger.debug(function(){return"SABR captions data received for "+c});
l.L?l.N==null?l.logger.G(350058965,"Null loaded track meta data at captions data received"):r.PW(y,l.N,c*1E3):l.logger.G(350058965,"Null Representation at captions data received")},eUH=function(l,y){var r=[],c;
for(c in l.G.G)if(l.G.G.hasOwnProperty(c)){var O=l.G.G[c];if(g.Wy(O,y||null)){var H=O.info.id,V=H,T="."+H,f="",N="";if(O=O.info.captionTrack)H=O.languageCode,V=O.displayName,T=O.vssId,f=O.kind,N=O.id;r.push(new g.Ir({id:c,languageCode:H,languageName:V,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:T,kind:f,captionId:N}))}}return r},n_z=function(l,y,r){var c=[],O;
for(O in l.G.G)if(l.G.G.hasOwnProperty(O)){var H=l.G.G[O];if(g.Wy(H,r||null)){var V=H.info.captionTrack;V&&V.languageCode===y&&c.push(H)}}return c.length?c[0]:null},bgb=function(l,y){if(!g.gIf(l)||l.G!=null&&g.BK(y.D())&&!l.G.isManifestless&&l.G.G.rawcc!=null)return!1;
y=!!l.G&&l.G.isManifestless&&Object.values(l.G.G).some(function(r){return g.Wy(r,"386")});
l=!!l.G&&!l.G.isManifestless&&g.Z1N(l.G);return y||l},P8=function(){AR.call(this)},RUg=function(l,y,r,c,O,H,V,T,f){switch(V.tagName){case "b":T.bold=!0;
break;case "i":T.italic=!0;break;case "u":T.underline=!0}for(var N=0;N<V.childNodes.length;N++){var S=V.childNodes[N];if(S.nodeType===3)S=new qs(y,r,c,O.id,S.nodeValue,H||N>0,g.GR(T)?void 0:T),f.push(S),O.G.push(S);else{var F={};Object.assign(F,T);RUg(l,y,r,c,O,!0,S,F,f)}}},Uzj=function(l){var y=l.split(":");
l=0;y=g.a(y);for(var r=y.next();!r.done;r=y.next())l=l*60+Number(r.value);return l*1E3},zUQ=function(l,y,r,c){c=Object.assign({zo:0},c);
return new W8(l,y,r,"_"+mr++,c)},xA=function(l,y){g.X.call(this);
this.V=l;this.GD=y;this.G=null;this.K=this.V.lV();this.logger=new g.NG("caps")},j8B=function(l,y,r){if(typeof y==="string"||t4J(y))return[{trackData:y,
h1:r}];var c=new DataView(y);if(c.byteLength<=8||c.getUint32(4)!==1718909296)return[];var O=g.mnv(c);if(l.K&&O){var H=g.aWd(O),V=g.sed(O);O=O.V6;H&&O&&l.K.WQ(O,H,V)}l=g.Cv(c,1835295092);if(!l||!l.length||!l[0].size)return[];H=[];for(V=0;V<l.length;V++)O=l[V],O=new Uint8Array(y,O.dataOffset,O.size-(O.dataOffset-O.offset)),O=g.td(O),H.push({trackData:O,h1:r+V*1E3});kos(c,H,r);return H=H.filter(function(T){return!!T.trackData})},kos=function(l,y,r){var c=g.jB(l,0,1836476516),O=9E4;
c&&(O=g.L$(c)||9E4);c=0;for(var H=g.Cv(l,1836019558),V=0;V<H.length;V++){var T=H[V];V<y.length&&(T=g.jB(l,T.dataOffset,1953653094))&&(T=g.jB(l,T.dataOffset,1952867444))&&(T=g.HW(T)/O*1E3,V===0&&(c=T),y[V].h1=T-c+r||r*V*1E3)}},LLB=function(l){var y={};
if(l=g.A1(l))y.lang=l,g.Xxp.test(l)&&(y.z0=1);return y},eS=function(l){g.IG.call(this,l);
var y=this;this.V=l;this.II=[];this.Nf={};this.Sj={};this.W=!1;this.B="NONE";this.G=this.X=this.Kq=this.ZZ=this.Y7=null;this.cg={WA:function(){y.WA()},
PW:function(H,V,T,f){y.PW(H,V,T,f)}};
this.K=null;this.GD=this.V.D();this.videoData=this.V.getVideoData();this.l8=this.V.TD();var r;this.vT=(r=this.V.getVideoData(1))==null?void 0:g.rp(r);this.N={wX:{}};this.L={wX:{}};g.Vb(this.videoData)?this.B="OFFLINE":bgb(this.videoData,this.V)?this.B="SABR_LIVE":g.iAN(this.videoData,this.V)?this.B="LIVE":this.videoData.captionTracks.length?this.B="INNERTUBE":this.videoData.rY&&(this.B="TTS");this.qf=this.GD.controlsType==="3";this.Qr=new xA(this.V,this.GD);this.Uz=new g.n4(this);this.J=new g.n({U:"div",
Z:"ytp-caption-window-container",Y:{id:"ytp-caption-window-container"}});this.i8={top:0,right:0,bottom:0,left:0,width:1,height:1};r=null;var c=g.wD("yt-html5-player-modules::subtitlesModuleData");c&&(r=new g.Za(c));this.storage=r;var O;this.w9=!((O=l.dX())==null||!O.fg());this.C=lMH(this);this.Mf=!this.C&&this.qf&&this.w9&&(this.B==="LIVE"||this.B==="SABR_LIVE");g.Q(this,this.Qr);this.C?this.r9=this.Cq=null:(this.Cq=new g.la(this.jX,void 0,this),g.Q(this,this.Cq),this.r9=new g.yU(this.ajA,2E3,this),
g.Q(this,this.r9));g.Q(this,this.Uz);g.wQ(this.player,this.J.element,4);g.Q(this,this.J);this.C||this.Uz.S(l,"resize",this.rH);(this.UF=g.ww(this.GD)&&!g.q5()&&!this.V.isFullscreen()&&!this.C&&!this.Mf)&&this.Uz.S(l,"resize",this.P2q);this.Uz.S(l,"onPlaybackAudioChange",this.pof);this.Uz.S(l,g.Eg("captions"),function(H){y.onCueRangeEnter(H)});
this.Uz.S(l,g.uw("captions"),function(H){y.onCueRangeExit(H)});
this.vT&&this.Uz.S(l,"videodatachange",function(H,V){y.onVideoDataChange(H,V)});
yyj(this,xoJ()||{});this.player.YX("onCaptionsModuleAvailable")},OPB=function(l){if(l.GD.w9===1||l.videoData.V$===1||g.hJ(l.videoData,"yt:cc")==="alwayson")return!0;
if(l.videoData.captionTracks.length)var y=l.getAudioTrack().K;if(l.GD.w9===2){if(g.O8(l.GD))var r=ryg(l);else if(l.storage)try{r=l.storage.get("module-enabled")}catch(O){l.storage.remove("module-enabled")}else r=null;if(r!=null)return!!r}r=BAH(l.player.getAudioTrack(),g.O8(l.GD));var c=g.hJ(l.videoData,"yt:cc");if(cyx(l)===void 0){if(r==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return c?c==="on":!0;if(r==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return c==="on"}else return c==="on";return y==="ON"||
g.hJ(l.videoData,"yt:cc")==="on"},nE=function(l,y){if(l.K&&(y===void 0||!y)||!l.videoData.captionTracks.length)return!1;
l=l.getAudioTrack();return!!l.G||l.K==="FORCED_ON"},cyx=function(l){var y=void 0,r=g.Ry(g.bm(),65);
if(g.O8(l.GD)&&r!=null){if(ryg(l)!=null)return!1;y=!r}return y},RD=function(l,y){if(!l.G)return null;
if(l.X&&l.X.B)return l.X.B;y=HPj(l,y);y=g.TB(l.G.K,y);var r=null;if(txz(l.GD)){var c=l.V.isInline()?void 0:g.QD("yt-player-caption-sticky-language");for(var O=[c,l.videoData.captionsLanguagePreference,l.GD.captionsLanguagePreference,g.hJ(l.videoData,"yt:cc_default_lang")],H=!1,V=0;V<O.length;V++){var T=O[V];if(T){H=!0;for(var f=0;f<y.length;f++)if(g.A1(y[f])===T)return y[f];for(f=0;f<y.length;f++)if(g.A1(y[f]).split("-")[0]===T.split("-")[0])return y[f]}}if(H&&l.G&&(O=l.G.C,O.length))for(O=g.a(O),
H=O.next();!H.done;H=O.next())if(H=H.value,H.languageCode===c){r=H;break}}else for(c=[l.videoData.captionsLanguagePreference,l.GD.captionsLanguagePreference,g.hJ(l.videoData,"yt:cc_default_lang")],O=0;O<c.length;O++)for(H=0;H<y.length;H++)if(g.A1(y[H])===c[O])return y[H];c=null;l.X&&l.X.N&&(c=l.X.N);c||(c=y.find(function(N){return N.isDefault})||null);
c||(c=y[0]||b0(l));c&&r&&g.A1(c).split("-")[0]!==r.languageCode.split("-")[0]&&(c=DoB(c,r));return c},b0=function(l){return l.X&&l.X.G},Uu=function(l){var y=b0(l);
return!!y&&l.K===y},VIz=function(l,y){var r=l.V.dX().Nh().textTracks;
l=l.K.toString();for(var c=0;c<r.length;c++){var O=r[c];O.id===l&&(y?O.mode!=="showing"&&(O.mode="showing"):O.mode==="showing"&&(O.mode="disabled"))}},jS=function(l,y,r){l.loaded&&l.unload();
r!=null&&(l.W=r,l.W&&(g.O8(l.GD)?zq(l,!!y):kA(l,!!y)));Cdz(l,l.K,y,l.W,!1);l.K=y;nE(l)&&(y=b0(l),Cdz(l,l.K,y,l.W,!0),l.K=y);var c;gKp(l,(c=l.K)!=null?c:void 0);l.load()},fMJ=function(l,y){if(y instanceof W8){var r=l.Nf[y.id];
r&&r.K!==y&&(r.dispose(),delete l.Nf[y.id],r=null);r||(r=TrI(l,y))&&(l.Nf[y.id]=r)}else r=y.windowId,l.Sj[r]||(l.Sj[r]=[]),l.Sj[r].push(y)},TrI=function(l,y){var r=NrQ(l);
if(!r)return null;var c=l.K?g.A1(l.K):null;c&&g.Xxp.test(c)&&(y.params.z0=1);var O=l.l8.getPlayerSize();c=O.height*l.i8.height;O=O.width*l.i8.width;l.GD.playerStyle!=="google-live"||l.N.isDefault||Object.assign(y.params,l.N);switch(y.params.zo!=null?y.params.zo:y.G.length>1?1:0){case 1:return new D2(y,l.N,l.L,r.width,r.height,O,c,l.GD.experiments,l.JW.bind(l),l.V);case 2:return new wL(y,l.N,l.L,r.width,r.height,O,c,l.GD.experiments,l.JW.bind(l),l.V);default:return new FM(y,l.N,l.L,r.width,r.height,
O,c,l.GD.experiments,l.JW.bind(l),l.V)}},yyj=function(l,y,r){r=r===void 0?!1:r;
var c=LE.wX;l.N={};Object.assign(l.N,LE);l.N.wX={};Object.assign(l.N.wX,c);l.L={wX:{}};var O=y.backgroundOverride?l.L:l.N,H=y.background||c.background;Gq.test(H);O.wX.background=H;O=y.colorOverride?l.L:l.N;H=y.color||c.color;Gq.test(H);O.wX.color=H;O=y.windowColorOverride?l.L:l.N;H=y.windowColor||LE.windowColor;Gq.test(H);O.windowColor=H;O=y.backgroundOpacityOverride?l.L:l.N;H=y.backgroundOpacity;H==null&&(H=c.backgroundOpacity);O.wX.backgroundOpacity=H;O=y.fontSizeIncrementOverride?l.L:l.N;H=y.fontSizeIncrement;
H==null&&(H=c.fontSizeIncrement);O.wX.fontSizeIncrement=H;H=y.fontStyleOverride?l.L:l.N;O=y.fontStyle;O==null&&(O=c.bold&&c.italic?3:c.bold?1:c.italic?2:0);H=H.wX;switch(O){case 1:H.bold=!0;delete H.italic;break;case 2:delete H.bold;H.italic=!0;break;case 3:H.bold=!0;H.italic=!0;break;default:delete H.bold,delete H.italic}O=y.textOpacityOverride?l.L:l.N;H=y.textOpacity;H==null&&(H=c.textOpacity);O.wX.textOpacity=H;O=y.windowOpacityOverride?l.L:l.N;H=y.windowOpacity;H==null&&(H=LE.windowOpacity);O.windowOpacity=
H;O=y.charEdgeStyleOverride?l.L:l.N;H=y.charEdgeStyle;H==null&&(H=c.charEdgeStyle);O.wX.charEdgeStyle=H;O=y.fontFamilyOverride?l.L:l.N;H=y.fontFamily;H==null&&(H=c.fontFamily);O.wX.fontFamily=H;l.loaded&&l.rH();r&&g.XI("yt-player-caption-display-settings",y,2592E3)},SVJ=function(l,y){if(!l.G)return{};
if(y){g.GR(y)||l.a9(y.vss_id,"m");if(l.C||!g.Rm(y))return;if(g.GR(y)){jS(l,null,!0);return}for(var r,c=g.TB(l.G.K,!0),O=0;O<c.length;O++){var H=c[O];H.languageCode!==y.languageCode||r&&(H.languageName!==y.languageName||(H.captionId||"")!==(y.captionId||"")||g.YO(H)!==y.displayName)||(r=y.translationLanguage?DoB(H,y.translationLanguage):H)}l.OQ(y.position);!r||r===l.K&&l.loaded||(y=g.z8(),c=g.A1(r),y.length&&c===y[y.length-1]||(y.push(c),g.XI("yt-player-caption-language-preferences",y)),txz(l.GD)&&
!l.V.isInline()&&g.XI("yt-player-caption-sticky-language",c,2592E3),jS(l,r,!0))}else return l.loaded&&l.K&&!Uu(l)?g.qL(l.K):{};return""},pAp=function(l,y,r){y&&!l.Kq?(y=o_Q({z0:0,
lang:"en"}),l.Kq=[y,new qs(y.start,y.end-y.start,0,y.id,r!=null?r:"Captions look like this")],l.player.v7(l.Kq)):!y&&l.Kq&&(F2x(l,l.Kq),l.Kq=null)},F2x=function(l,y){l.player.Pn(y);
y=g.a(y);for(var r=y.next();!r.done;r=y.next())g.jH(l.II,r.value);fE(l.Cq)},gKp=function(l,y){l.GD.j("html5_modify_caption_vss_logging")&&(l.videoData.M9=y)},NrQ=function(l){var y=l.l8.getVideoContentRect(!0).height,r=l.l8.getVideoContentRect(!0).width;
if(!y||!r)return null;y*=l.i8.height;r*=l.i8.width;return{width:r,height:y}},kA=function(l,y){if(l.storage)try{l.storage.set("module-enabled",y)}catch(r){}},zq=function(l,y){l.V.isInline()||g.XI("yt-player-sticky-caption",y,2592E3)},ryg=function(l){if(!l.V.isInline())return g.QD("yt-player-sticky-caption")},lMH=function(l){if(l.GD.j("safari_live_drm_captions_fix")&&l.videoData.Qq()&&l.videoData.Ve()&&g.Wj)return!0;
var y,r=!((y=l.V.dX())==null||!y.gq());return l.qf&&r&&l.B!=="LIVE"&&l.B!=="SABR_LIVE"},HPj=function(l,y){g.eF(l.videoData)&&(y=!0);
y||(y=l.B==="TTS"?!1:l.B==="INNERTUBE"?!1:!0);return y||l.GD.j("web_deprecate_always_includes_asr_setting")&&g.O8(l.GD)?!0:!!g.Ry(g.bm(),66)},Cdz=function(l,y,r,c,O){O?l.nf(r,!0,"g"):c?y?l.nf(r,!!r,"m"):r&&l.nf(r,!0,"m"):!y&&r&&l.nf(r,!0,"s")};
g.q3.prototype.vj=g.cz(77,function(){return!1});
g.q3.prototype.LL=g.cz(76,function(){});
g.AK.prototype.LL=g.cz(75,function(l,y,r){var c=this;this.Lq();y=this.bY(l,y);var O=this.fq.D().j("html5_report_captions_ctmp_qoe"),H=(0,g.$$)();this.fI();$op(this,y,{format:"RAW",onSuccess:function(V){c.G=null;if(O){var T=(V.responseText.length/1024).toFixed(),f=(0,g.$$)();c.videoData.AC("capresp",{ms:f-H,kb:T})}r.PW(V.responseText,l)},
onError:O?function(V){var T;V=(T=V==null?void 0:V.status)!=null?T:0;c.videoData.AC("capfail",{status:V})}:void 0,
withCredentials:!0})});
g.mV.prototype.LL=g.cz(74,function(l,y,r){var c=this;this.Lq();y=this.bY(l,y);this.fI();this.G=g.Gd(y,{format:"RAW",onSuccess:function(O){c.G=null;r.PW(O.responseText,l)},
withCredentials:!0})});
g.rU.prototype.TE=g.cz(73,function(){for(var l=g.UR(document,"track",void 0,this.G),y=0;y<l.length;y++)g.Cg(l[y])});
g.BM.prototype.TE=g.cz(72,function(){this.mediaElement.TE()});
g.rU.prototype.fg=g.cz(71,function(){return!(!this.G.textTracks||!this.G.textTracks.addEventListener)});
g.BM.prototype.fg=g.cz(70,function(){return this.mediaElement.fg()});
g.rU.prototype.gq=g.cz(69,function(){return!!this.G.textTracks});
g.BM.prototype.gq=g.cz(68,function(){return this.mediaElement.gq()});
g.rU.prototype.Jh=g.cz(67,function(l){for(var y=0;y<l.length;y++)this.G.appendChild(l[y])});
g.BM.prototype.Jh=g.cz(66,function(l){this.mediaElement.Jh(l)});
g.Vm.prototype.WQ=g.cz(65,function(l,y,r){this.sy.WQ(l,y,r)});
g.nA.prototype.WQ=g.cz(64,function(l,y,r){this.K.set(l,{vM:y,Z9:r})});
g.bW.prototype.WQ=g.cz(63,function(l,y,r){this.Cq.WQ(l,y,r)});
g.Vm.prototype.e$=g.cz(62,function(l){return this.sy.e$(l)});
g.bW.prototype.e$=g.cz(61,function(l){var y=2;this.W.has(l)?y=0:g.EpC(this,l)&&(y=1);return y});
g.$h.prototype.Re=g.cz(49,function(l){var y=this.app.Tv();return y?y.Re(l):!1});
g.R9.prototype.Re=g.cz(48,function(l){return this.hC.h6.Re(l)});
g.xd.prototype.Re=g.cz(47,function(l){return this.iU().some(function(y){return y.namespace===l})});
g.XS.prototype.Re=g.cz(46,function(){return!1});
g.$h.prototype.a9=g.cz(44,function(l,y){var r;(r=this.app.zD())==null||r.a9(l,y)});
g.R9.prototype.a9=g.cz(43,function(l,y){this.hC.a9(l,y)});
g.WF.prototype.a9=g.cz(42,function(l,y){l=[l,y];g.Ax(this,g.HF(this.provider),"cfi",l)});
g.Qm.prototype.a9=g.cz(41,function(l,y){this.qoe&&this.qoe.a9(l,y)});
g.Fa.prototype.a9=g.cz(40,function(l,y){this.gA().a9(l,y)});
g.XS.prototype.a9=g.cz(39,function(){});
g.$h.prototype.nf=g.cz(38,function(l,y,r){var c;(c=this.app.zD())==null||c.nf(l,y,r)});
g.R9.prototype.nf=g.cz(37,function(l,y,r){this.hC.nf(l,y,r)});
g.WF.prototype.nf=g.cz(36,function(l,y,r){if(this.r9!==l||this.Hg!==y)y=y==="rawcc"?"":y,r=[l,y,this.r9,r],g.Ax(this,g.HF(this.provider),"cfs",r),this.r9=l,this.Hg=y});
g.Qm.prototype.nf=g.cz(35,function(l,y,r){this.qoe&&this.qoe.nf(l,y,r)});
g.Fa.prototype.nf=g.cz(34,function(l,y,r){this.gA().nf(l,y,r)});
g.XS.prototype.nf=g.cz(33,function(){});
g.cF.prototype.lB=g.cz(20,function(){return this.W});
g.af.prototype.lB=g.cz(19,function(){var l;return((l=this.zD())==null?void 0:l.lV())||null});
g.$h.prototype.lV=g.cz(18,function(){return this.app.lB()});
g.R9.prototype.lV=g.cz(17,function(){return this.hC.lV()});
g.Fa.prototype.lV=g.cz(16,function(){var l;return((l=this.Oz)==null?void 0:l.lB())||null});
g.XS.prototype.lV=g.cz(15,function(){return null});
g.d5.prototype.Ma=g.cz(1,function(l){return(l=this.qA(l))?l.G:0});
g.F9.prototype.Ma=g.cz(0,function(){return 0});
var QPJ=/#(.)(.)(.)/,X5Q=/^#(?:[0-9a-f]{3}){1,2}$/i,Uob={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};Ns.prototype.contains=function(l){l=g.CM(this.segments,l);return l>=0||l<0&&(-l-1)%2===1};
Ns.prototype.length=function(){return this.segments.length/2};
g.M(nTI,g.X);g.C=nTI.prototype;g.C.yr=function(){g.X.prototype.yr.call(this);this.N&&this.N.cancel()};
g.C.AY=function(){this.seekTo(this.player.getCurrentTime())};
g.C.seekTo=function(l){l-=this.player.lT();var y=this.G;this.G=g.np(this.Kq.nL(l).mR);y!==this.G&&this.X&&this.X()};
g.C.reset=function(){this.B=new Ns;this.L=-1;this.N&&(this.N.cancel(),this.N=null)};
g.C.WK=function(){this.Lq();var l;if(l=this.G!=null)l=this.G,l=l.G.IK(l);if(l&&!this.N&&!(this.G&&this.G.startTime-this.player.getCurrentTime()>30)){l=this.G;l=l.G.Fv(l);var y=l.mR[0],r;if((r=this.player.getVideoData())==null?0:r.enableServerStitchedDai)if(r=this.player.lV()){var c=y.G.info.id,O=y.jj,H=l.mR[0].B;if(this.policy.II){if(r=r.C7(H,O,c,3))l.B=r}else if(c=r.Cd(H,O,c,3))if(r=r.e$(O),r===0)c&&(l.G=new g.os(c));else if(r===2){this.J.start();bHg(this)&&this.seekTo(this.player.getCurrentTime());
return}}y.G.index.qv(y.jj)?(this.B.contains(l.mR[0].jj)||RpH(this,l),this.G=g.np(l.mR)):bHg(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.M(SS,g.q3);g.C=SS.prototype;g.C.LL=function(l,y,r){var c=this;this.fI();y=kRJ(this,l.getId());y||(y=l.languageCode,y=this.G.isManifestless?jPg(this,y,"386"):jPg(this,y));if(y){var O=(y.index.Ma(y.index.mV())-y.index.getStartTime(y.index.mV()))*1E3,H=this.V.D(),V=new g.xBv(H),T=function(){c.N&&c.N.reset();c.L=!0};
H.j("html5_keep_caption_data_after_seek")&&(T=null);this.N=new nTI(V,this.V,y,function(f,N){r.PW(f,l,N,O)},this.J||g.C1(y.info),T)}};
g.C.vj=function(){var l=this.L;this.L=!1;return l};
g.C.v2=function(l){var y=this.V.D().j("html5_fallback_if_rawcc_missing");var r=this.G.G.rawcc!=null;if(!this.J||!r&&y)y=this.G.isManifestless?zpg(this,"386"):zpg(this);else{if(!r){this.logger.G(386248249,"rawcc used but unavailable");return}y=[new g.Ir({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Ir({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}y=g.a(y);
for(r=y.next();!r.done;r=y.next())g.Ym(this.K,r.value);l.WA()};
g.C.fI=function(){this.N&&(this.N.dispose(),this.N=null)};
g.C.bY=function(){return""};
g.C.D6=function(){this.N&&(this.N.reset(),this.V.sX("captions"))};
var Gq=/^#(?:[0-9a-f]{3}){1,2}$/i;var yZQ=["left","right","center","justify"];g.M(FM,g.n);g.C=FM.prototype;g.C.Pa=function(l,y){this.vT=l;this.Y7=y;var r=g.JH(this.element,this.element.parentElement);this.l8=l-r.x;this.w9=y-r.y};
g.C.Yd=function(l,y){if(l!==this.vT||y!==this.Y7){g.fU(this.element,"ytp-dragging")||g.Nr(this.element,"ytp-dragging");var r=g.hH(this.element);l=l-this.l8-.02*this.playerWidth;var c=y-this.w9-.02*this.playerHeight,O=(l+r.width/2)/this.maxWidth*3;O=Math.floor(g.Sx(O,0,2));var H=(c+r.height/2)/this.maxHeight*3;H=Math.floor(g.Sx(H,0,2));y=O+H*3;l=(l+O/2*r.width)/this.maxWidth;l=g.Sx(l,0,1)*100;r=(c+H/2*r.height)/this.maxHeight;r=g.Sx(r,0,1)*100;this.K.params.Cb=y;this.K.params.g7=r;this.K.params.e9=
l;this.K.params.isDefault=!1;this.G.Cb=y;this.G.g7=r;this.G.e9=l;this.G.isDefault=!1;this.i8.Cb=y;this.i8.g7=r;this.i8.e9=l;this.i8.isDefault=!1;this.XM()}};
g.C.lE=function(){g.Fb(this.element,"ytp-dragging")};
g.C.XM=function(){this.Jr(this.J)};
g.C.getType=function(){return this.type};
g.C.Jr=function(l){var y=this.cg?0:Math.min(this.qJ(),this.maxWidth),r=this.ub(),c=this.cg;if(c){var O=getComputedStyle(this.B.parentNode);O=pE(O.borderLeftWidth)+pE(O.borderRightWidth)+pE(O.paddingLeft)+pE(O.paddingRight)}else O=0;var H=O;O="";this.K.params.z0===3&&(O="rotate(180deg)");var V=c?"calc(96% - "+H+"px)":"96%";g.ET(this.element,{top:0,left:0,right:"",bottom:"",width:y?y+"px":"",height:r?r+"px":"","max-width":V,"max-height":V,margin:"",transform:""});this.eb(l);O={transform:O,top:"",left:"",
width:y?y+"px":"",height:r?r+"px":"","max-width":"","max-height":""};var T=this.G.e9*.96+2;V=this.G.Cb;switch(V){case 0:case 3:case 6:(c=this.G.wX.fontSizeIncrement)&&c>0&&this.G.z0!==2&&this.G.z0!==3&&(T=Math.max(T/(1+c*2),2));O.left=T+"%";break;case 1:case 4:case 7:O.left=T+"%";T=this.B.offsetWidth;y||T?(y=y||T+1,O.width=y+"px",O["margin-left"]=c?y/-2-H/2+"px":y/-2+"px"):O.transform+=" translateX(-50%)";break;case 2:case 5:case 8:O.right=100-T+"%"}c=this.G.g7*.96+2;switch(V){case 0:case 1:case 2:O.top=
c+"%";break;case 3:case 4:case 5:O.top=c+"%";(r=r||this.element.clientHeight)?(O.height=r+"px",O["margin-top"]=r/-2+"px"):O.transform+=" translateY(-50%)";break;case 6:case 7:case 8:O.bottom=100-c+"%"}g.ET(this.element,O);if(this.L){r=this.B.offsetHeight;c=1;for(y=0;y<l.length;y++)O=l[y],typeof O.text==="string"&&(c+=O.text.split("\n").length-1,O.append||y===0||c++);r/=c;this.L.style.height=r+"px";this.L.style.width=r+"px";this.element.style.paddingLeft=r+5+"px";this.element.style.paddingRight=r+
5+"px";l=Number(this.element.style.marginLeft.replace("px",""))-r-5;r=Number(this.element.style.marginRight.replace("px",""))-r-5;this.element.style.marginLeft=l+"px";this.element.style.marginRight=r+"px"}};
g.C.eb=function(l){var y;for(y=0;y<l.length&&l[y]===this.J[y];y++);if(this.Mf||this.J.length>y)y=0,this.Mf=!1,this.J=[],this.W=this.Cq=this.II=null,g.H7(this.B);for(;y<l.length;y++)V4b(this,l[y])};
g.C.qJ=function(){return 0};
g.C.ub=function(){return 0};
g.C.toString=function(){return g.n.prototype.toString.call(this)};g_Q.prototype.clear=function(){this.N=this.time=this.mode=0;this.G=[];this.reset()};
g_Q.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var TCs=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Eu.prototype.set=function(l){this.type=l};
Eu.prototype.get=function(){return this.type};
u0.prototype.clear=function(){this.state=0};
u0.prototype.update=function(){this.state=this.state===2?1:0};
u0.prototype.eO=function(){return this.state!==0};
u0.prototype.matches=function(l,y){return this.eO()&&l===this.JI&&y===this.Wi};
p7B.prototype.reset=function(){this.timestamp=this.G=0};
Ms.prototype.updateTime=function(l){for(var y=1;y<=15;++y)for(var r=1;r<=32;++r)this.N[y][r].timestamp=l};
Ms.prototype.debugString=function(){for(var l="\n",y=1;y<=15;++y){for(var r=1;r<=32;++r){var c=this.N[y][r];l=c.G===0?l+"_":l+String.fromCharCode(c.G)}l+="\n"}return l};
Ms.prototype.reset=function(l){for(var y=0;y<=15;y++)for(var r=0;r<=32;r++)this.N[y][r].reset();this.B=l;this.G=0;this.K=this.row=1};
var E_H=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],uLB=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],M4J=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],anb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Yeg.prototype.reset=function(l,y){this.C=y;this.style.set(2);this.K=this.L;this.B=this.J;this.G=this.K;var r=(l<<2)+(y<<1);this.L.reset(r);this.J.reset(r);this.text.reset((l<<2)+(y<<1)+1)};
Ctz.prototype.reset=function(l){this.C=l;this.K.clear();this.B=this.N;this.N.reset(l,0);this.L.reset(l,1)};mzj.prototype.B=function(){};g.M(qs,g.F8);qs.prototype.toString=function(){return g.F8.prototype.toString.call(this)};g.M(AR,g.X);AR.prototype.MK=function(){return[]};
AR.prototype.reset=function(){};g.M(W8,g.F8);W8.prototype.toString=function(){return g.F8.prototype.toString.call(this)};
var mr=0;g.M(v8,AR);v8.prototype.reset=function(){this.L={};this.K=this.G=null;this.C=!0};
v8.prototype.MK=function(l,y){l=l.firstChild;l.getAttribute("format");y=y||0;Number.isFinite(y);l=Array.from(l.childNodes);l=g.a(l);for(var r=l.next();!r.done;r=l.next())if(r=r.value,r.nodeType===1)switch(r.tagName){case "head":var c=r;break;case "body":var O=r}if(c)for(c=Array.from(c.childNodes),c=g.a(c),l=c.next();!l.done;l=c.next())if(l=l.value,l.nodeType===1)switch(l.tagName){case "pen":r=l.getAttribute("id");var H=this.pens,V={},T=l.getAttribute("p");T&&Object.assign(V,this.pens[T]);T=oD(l,"b");
T!=null&&(V.bold=T);T=oD(l,"i");T!=null&&(V.italic=T);T=oD(l,"u");T!=null&&(V.underline=T);T=hR(l,"et");T!=null&&(V.charEdgeStyle=T);T=hR(l,"of");T!=null&&(V.offset=T);T=Z2(l,"bc");T!=null&&(V.background=T);T=Z2(l,"ec");T!=null&&(V.nm=T);T=Z2(l,"fc");T!=null&&(V.color=T);T=hR(l,"fs");T!=null&&T!==0&&(V.fontFamily=T);T=JR(l,"sz");T!==void 0&&(V.fontSizeIncrement=T/100-1);T=JR(l,"bo");T!==void 0&&(V.backgroundOpacity=T/255);T=JR(l,"fo");T!==void 0&&(V.textOpacity=T/255);T=hR(l,"rb");T!=null&&T!==10&&
T!==0&&(V.EZ=T>10?T-1:T);l=hR(l,"hg");l!=null&&(V.zQ=l);H[r]=V;break;case "ws":r=l.getAttribute("id");this.W[r]=hUb(this,l);break;case "wp":r=l.getAttribute("id"),this.J[r]=GoJ(this,l)}if(O){c=[];O=Array.from(O.childNodes);O=g.a(O);for(l=O.next();!l.done;l=O.next())if(l=l.value,l.nodeType===1)switch(l.tagName){case "w":this.G=ZgJ(this,l,y,!1);(l=this.L[this.G.id])&&l.end>this.G.start&&(l.end=this.G.start);this.L[this.G.id]=this.G;c.push(this.G);break;case "p":var f=l;T=y;r=[];H=f.getAttribute("w")||
this.B;V=!!oD(f,"a");T=(JR(f,"t")||0)+T;var N=JR(f,"d")||5E3;V||(!this.C&&this.K&&this.K.windowId===H&&this.K.end>T&&(this.K.end=T),this.K&&this.K.text==="\n"&&(this.K.text=""));var S=V?6:5,F=f.getAttribute("p");F=F?this.pens[F]:null;var p=Array.from(f.childNodes);p.length&&(this.C=f.getAttribute("d")!=null);for(f=0;f<p.length;f++){var E=p[f],u=void 0;f>0&&(V=!0);var I=void 0;E.nodeType===1&&(I=E);if(I&&I.tagName==="s"){if((E=(E=I.getAttribute("p"))?this.pens[E]:null)&&E.EZ&&(E.EZ===1?(E=p.slice(f,
f+4),E.length===4&&(u=JZs(T,N,H,V,S,E,this.pens),f+=3)):u=JZs(T,N,H,V,S,[I],this.pens)),!u){var q=I;u=T;I=N;E=H;var W=V,v=S,G=q.textContent?q.textContent:"",D=q.getAttribute("p");D=D?this.pens[D]:null;q=JR(q,"t")||0;u=new qs(u+q,I-q,v,E,G,W,D)}}else u=new qs(T,N,S,H,E.textContent||"",V,F);r.push(u);this.K=u}if(r.length>0)for(r[0].windowId===this.B&&(this.G=ZgJ(this,l,y,!0),c.push(this.G)),l=g.a(r),r=l.next();!r.done;r=l.next())r=r.value,r.windowId=this.G.id,this.G.G.push(r),c.push(r)}y=c}else y=[];
return y};var EKg=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.M($A,AR);$A.prototype.reset=function(){this.K.clear()};
$A.prototype.MK=function(l,y){var r=JSON.parse(l);if(!r)return[];if(r.pens){l=0;for(var c=g.a(r.pens),O=c.next();!O.done;O=c.next()){O=O.value;var H={},V=O.pParentId;V&&Object.assign(H,this.G.get(V));O.bAttr&&(H.bold=!0);O.iAttr&&(H.italic=!0);O.uAttr&&(H.underline=!0);V=O.ofOffset;V!=null&&(H.offset=V);O.szPenSize!==void 0&&(H.fontSizeIncrement=O.szPenSize/100-1);V=O.etEdgeType;V!=null&&(H.charEdgeStyle=V);O.ecEdgeColor!==void 0&&(H.nm=B8(O.ecEdgeColor));V=O.fsFontStyle;V!=null&&V!==0&&(H.fontFamily=
V);O.fcForeColor!==void 0&&(H.color=B8(O.fcForeColor));O.foForeAlpha!==void 0&&(H.textOpacity=O.foForeAlpha/255);O.bcBackColor!==void 0&&(H.background=B8(O.bcBackColor));O.boBackAlpha!==void 0&&(H.backgroundOpacity=O.boBackAlpha/255);(V=O.rbRuby)&&V!==10&&(H.EZ=V>10?V-1:V,H.textEmphasis=EKg.get(H.EZ));O.hgHorizGroup&&(H.zQ=O.hgHorizGroup);this.G.set(l++,H)}}if(r.wsWinStyles)for(l=0,c=g.a(r.wsWinStyles),O=c.next();!O.done;O=c.next())O=O.value,H={},(V=O.wsParentId)?Object.assign(H,this.B.get(V)):Object.assign(H,
this.C),O.mhModeHint!==void 0&&(H.zo=O.mhModeHint),O.juJustifCode!==void 0&&(H.textAlign=O.juJustifCode),O.pdPrintDir!==void 0&&(H.z0=O.pdPrintDir),O.sdScrollDir!==void 0&&(H.bP=O.sdScrollDir),O.wfcWinFillColor!==void 0&&(H.windowColor=B8(O.wfcWinFillColor)),O.wfoWinFillAlpha!==void 0&&(H.windowOpacity=O.wfoWinFillAlpha/255),this.B.set(l++,H);if(r.wpWinPositions)for(l=0,c=g.a(r.wpWinPositions),O=c.next();!O.done;O=c.next())O=O.value,H={},(V=O.wpParentId)&&Object.assign(H,this.N.get(V)),O.ahHorPos!==
void 0&&(H.e9=O.ahHorPos),O.apPoint!==void 0&&(H.Cb=O.apPoint),O.avVerPos!==void 0&&(H.g7=O.avVerPos),O.ccCols!==void 0&&(H.Da=O.ccCols),O.rcRows!==void 0&&(H.XA=O.rcRows),this.N.set(l++,H);if(r.events){l=[];r=g.a(r.events);for(c=r.next();!c.done;c=r.next()){var T=c.value;O=(T.tStartMs||0)+y;H=T.dDurationMs||0;if(T.id)V=String(T.id),c=$zB(this,T,O,H,V),l.push(c),this.K.set(V,c);else{T.wWinId?V=T.wWinId.toString():(V="_"+mr++,c=$zB(this,T,O,H,V),l.push(c),this.K.set(V,c));c=l;var f=T;H===0&&(H=5E3);
T=this.K.get(V);var N=!!f.aAppend,S=N?6:5,F=f.segs,p=null;f.pPenId&&(p=this.G.get(f.pPenId));for(f=0;f<F.length;f++){var E=F[f],u=E.utf8;if(u){var I=E.tOffsetMs||0,q=null;E.pPenId&&(q=this.G.get(E.pPenId));if((T.params.zo!=null?T.params.zo:T.G.length>1?1:0)===2&&N&&u==="\n")continue;E=null;var W=[],v;if(v=q&&q.EZ===1){v=F;var G=f;if(G+3>=v.length||!v[G+1].pPenId||!v[G+2].pPenId||!v[G+3].pPenId)v=!1;else{var D=v[G+1].pPenId;(D=this.G.get(D))&&D.EZ&&D.EZ===2?(D=v[G+2].pPenId,D=this.G.get(D),!D||!D.EZ||
D.EZ<3?v=!1:(D=v[G+3].pPenId,v=(D=this.G.get(D))&&D.EZ&&D.EZ===2?!0:!1)):v=!1}}if(v)I=F[f+1].utf8,E=F[f+3].utf8,v=F[f+2].utf8,G=this.G.get(F[f+2].pPenId),u=v_J(u,I,v,E,G),E=new qs(O,H,S,V,u,N,q),f+=3;else{if(u.indexOf("<")>-1){var w=void 0;W=q;v=p;G=O;D=H;var U=I,R=S,ON=N,Cl=[],ls=g.Up("<html>"+u+"</html>");if(!ls.getElementsByTagName("parsererror").length&&((w=ls.firstChild)==null?0:w.childNodes.length))for(w=g.a(ls.firstChild.childNodes),ls=w.next();!ls.done;ls=w.next()){ls=ls.value;var x=void 0,
L=void 0,K=(L=(x=ls.textContent)==null?void 0:x.replace(/\n/g,""))!=null?L:"";if(ls.nodeType!==3||K&&K.match(/^ *$/)==null){x={};Object.assign(x,W||v);L=void 0;switch((L=ls)==null?void 0:L.tagName){case "b":x.bold=!0;break;case "i":x.italic=!0;break;case "u":x.underline=!0}Cl.push(new qs(G+U,D-U,R,T.id,K,ON,x))}}W=Cl}W.length||(W=[new qs(O+I,H-I,S,T.id,u,N,q||p)])}if(W.length)for(N=g.a(W),q=N.next();!q.done;q=N.next())q=q.value,c.push(q),T.G.push(q);else E&&(c.push(E),T.G.push(E))}N=!0}}}y=l}else y=
[];return y};g.M(tR,g.q3);tR.prototype.LL=function(l,y,r){iHg(this.videoData.videoId,l.vssId,r.PW)};
tR.prototype.v2=function(l){if(this.audioTrack)for(var y=g.a(this.audioTrack.captionTracks),r=y.next();!r.done;r=y.next())g.Ym(this.K,r.value);l.WA()};g.M(D2,FM);D2.prototype.eb=function(l){var y=this.K.G;FM.prototype.eb.call(this,l);for(l=l.length;l<y.length;l++){var r=y[l];if(H&&r.G===O)var c=H;else{c={};Object.assign(c,r.G);Object.assign(c,usJ);var O=r.G;var H=c}V4b(this,r,c)}};
var usJ={Hqw:!0};g.M(dL,mzj);dL.prototype.B=function(l,y,r,c,O){if(r<c){var H="_"+mr++;r=r/1E3-this.L;c=c/1E3-this.L;l=new W8(r,c-r,5,H,{textAlign:0,Cb:0,e9:y*2.5,g7:l*5.33});O=new qs(r,c-r,5,H,O);this.K.push(l);this.K.push(O)}};
g.M(QZ,AR);QZ.prototype.MK=function(l){l=new dL(l,l.byteLength,this.K);if(BCJ(l)){for(;l.byteOffset<l.G.byteLength;)for(l.version===0?l.N=XM(l)*(1E3/45):l.version===1&&(l.N=XM(l)*4294967296+XM(l)),l.C=i0(l);l.C>0;l.C--){var y=i0(l),r=i0(l),c=i0(l);y&4&&(y&3)===this.track&&(this.track===0||this.track===1)&&(y=this.G,y.G.push({time:l.N,type:this.track,ZF:r,SR:c,order:y.G.length}))}FLH(this.G,l);return l.K}return[]};
QZ.prototype.reset=function(){this.G.clear()};g.M(wL,FM);g.C=wL.prototype;g.C.XM=function(){g.c6(this.qf)};
g.C.cj=function(){this.Sj&&this.element.removeEventListener("transitionend",this.cj,!1);g.Fb(this.element,"ytp-rollup-mode");this.Jr(this.xN,!0)};
g.C.ub=function(){return this.N?this.Kq:this.X};
g.C.qJ=function(){return this.N?this.X:this.Kq};
g.C.Jr=function(l,y){this.xN=l;if(this.K.params.XA){for(var r=0,c=0;c<this.J.length&&r<l.length;c++)this.J[c]===l[r]&&r++;r>0&&r<l.length&&(l=this.J.concat(l.slice(r)));this.ez=this.Kq;this.X=this.Kq=0;FM.prototype.Jr.call(this,l);igp(this,y)}FM.prototype.Jr.call(this,l)};X7J.prototype.unload=function(){this.G!=null&&(this.V.removeEventListener("sabrCaptionsDataLoaded",this.G),this.G=null);this.FD=[];this.V.publish("sabrCaptionsBufferedRangesUpdated",this.FD)};
X7J.prototype.QZ=function(l){return{formatId:g.T3(l.info.G.info,this.Ve),jj:l.info.jj+(this.Ve?0:1),startTimeMs:l.info.B*1E3,durationMs:l.info.W*1E3}};g.M(xzs,g.q3);g.C=xzs.prototype;g.C.LL=function(l,y,r){this.fI();y=l.getId();y=y!=null&&y in this.G.G?this.G.G[y]:null;y||(y=l.languageCode,y=this.G.isManifestless?n_z(this,y,"386"):n_z(this,y));y&&(this.N=l,this.L=y,PtJ(this.J,r),this.V.publish("sabrCaptionsTrackChanged",g.T3(y.info,this.G.Ve)))};
g.C.v2=function(l){var y=this.G.isManifestless?eUH(this,"386"):eUH(this);y=g.a(y);for(var r=y.next();!r.done;r=y.next())g.Ym(this.K,r.value);l.WA()};
g.C.fI=function(){this.N&&(this.N=this.L=null,this.J.unload(),this.V.publish("sabrCaptionsTrackChanged",null))};
g.C.bY=function(){return""};
g.C.D6=function(){this.V.sX("captions")};g.M(P8,AR);
P8.prototype.MK=function(l,y){var r=[];l=l.split(MIj);for(var c=1;c<l.length;c++){var O=l[c],H=y;if(O!==""&&!aMH.test(O)){var V=sLj.exec(O);if(V&&V.length>=4){var T=Uzj(V[1]),f=Uzj(V[2])-T;T+=H;var N=(V=V[3])?V.split(" "):[];V={};var S=null;var F="";var p=null,E="";N=g.a(N);for(var u=N.next();!u.done;u=N.next())if(u=u.value.split(":"),u.length===2){var I=u[1];switch(u[0]){case "line":u=I.split(",");u[0].endsWith("%")&&(S=u[0],V.g7=Number.parseInt(S,10),u.length===2&&(F=u[1].trim()));break;case "position":u=
I.split(",");p=u[0];V.e9=Number.parseInt(p,10);u.length===2&&(E=u[1].trim());break;case "align":switch(I){case "start":V.textAlign=0;break;case "middle":V.textAlign=2;break;case "end":V.textAlign=1}}}S||F||(F="end");if(!p)switch(V.textAlign){case 0:V.e9=0;break;case 1:V.e9=100;break;case 2:V.e9=50}if(V.textAlign!=null){S=0;switch(F){case "center":S+=3;break;case "end":S+=6;break;default:S+=0}switch(E){case "line-left":S+=0;break;case "center":S+=1;break;case "line-right":S+=2;break;default:switch(V.textAlign){case 0:S+=
0;break;case 2:S+=1;break;case 1:S+=2}}F=S<0||S>8?7:S;V.Cb=F}O=O.substring(sLj.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");E=V;V=O;O={};if(V.indexOf("<")<0&&V.indexOf("&")<0)H=zUQ(T,f,5,E),f=new qs(T,f,5,H.id,V,!1,g.GR(O)?void 0:O),r.push(H),r.push(f),H.G.push(f);else for(F=V.split(K2H),F.length===1?(V=5,E=zUQ(T,f,V,E)):(S=V=6,E=Object.assign({Da:32},E),E=new W8(T,f,S,"_"+mr++,E)),r.push(E),S=T,p=0;p<F.length;p++)N=F[p],p%2===0?(u=g.Up("<html>"+N+"</html>"),u.getElementsByTagName("parsererror").length?
(I=u.createElement("span"),I.appendChild(u.createTextNode(N))):I=u.firstChild,RUg(this,S,f-(S-T),V,E,p>0,I,O,r)):S=Uzj(N)+H}sLj.lastIndex=0}}return r};
var aMH=/^NOTE/,MIj=/(?:\r\n|\r|\n){2,}/,sLj=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),K2H=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.tG.xo(P8,{MK:"wvppt"});g.M(xA,g.X);
xA.prototype.MK=function(l,y,r,c){c=c||0;r=j8B(this,l,r||0);l=[];try{for(var O=g.a(r),H=O.next();!H.done;H=O.next()){var V=H.value,T=V.trackData,f=V.h1;if(typeof T!=="string"){r=l;var N=r.concat,S=y,F=T,p=f,E=c;if(!t4J(F))throw Error("Invalid binary caption track data");this.G||(this.G=new QZ(E,S));var u=this.G.MK(F,p);var I=N.call(r,u)}else{if(T.substring(0,6)==="WEBVTT"){r=l;var q=r.concat;this.G||(this.G=new P8);var W=this.G.MK(T,f);Math.random()<.01&&g.Pv(Error("Deprecated subtitles format in web player: WebVTT"));var v=
q.call(r,W)}else{r=l;var G=r.concat;a:{S=y;if(T[0]==="{")try{this.G||(this.G=new $A(LLB(S)));var D=this.G.MK(T,f);break a}catch(ls){g.wV(ls);D=[];break a}var w=g.Up(T);if(!w||!w.firstChild){var U=Error("Invalid caption track data");U.params=T;throw U;}if(w.firstChild.tagName==="timedtext"){if(Number(w.firstChild.getAttribute("format"))===3){F=w;this.G||(this.G=new v8(LLB(S),this.GD));D=this.G.MK(F,f);break a}var R=Error("Unsupported subtitles format in web player (Format2)");R.params=T;throw R;}if(w.firstChild.tagName===
"transcript"){var ON=Error("Unsupported subtitles format in web player (Format1)");ON.params=T;throw ON;}var Cl=Error("Invalid caption track data");Cl.params=T;throw Cl;}v=G.call(r,D)}I=v}l=I}return l}catch(ls){return this.logger.G(187101178,"Captions parsing failed: "+ls.message+". "),this.clear(),[]}};
xA.prototype.clear=function(){this.G&&this.G.dispose();this.G=null};
xA.prototype.reset=function(){this.G&&this.G.reset()};
xA.prototype.yr=function(){g.X.prototype.yr.call(this);this.clear()};var LE={windowColor:"#080808",windowOpacity:0,textAlign:2,Cb:7,e9:50,g7:100,isDefault:!0,wX:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.M(eS,g.IG);g.C=eS.prototype;g.C.yr=function(){if(this.C||this.Mf){var l=this.V.dX();l&&!l.Lq()&&l.TE()}else pAp(this,!1);g.IG.prototype.yr.call(this)};
g.C.Hl=function(){return this.GD.j("html5_honor_caption_availabilities_in_audio_track")&&this.B!=="LIVE"&&this.B!=="SABR_LIVE"};
g.C.Ci=function(){if(this.qf)return this.C||this.Mf;var l=this.getAudioTrack();if(this.Hl()){if(!l.captionTracks.length)return!1;if(!this.G)return!0}l=BAH(l,g.O8(this.GD));return l==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:l==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?nE(this):cyx(this)||nE(this)?!0:OPB(this)};
g.C.load=function(){g.IG.prototype.load.call(this);this.X=this.getAudioTrack();if(this.G)this.K&&(this.Qr.clear(),this.C?VIz(this,!0):this.player.getPresentingPlayerType()!==3&&this.G.LL(this.K,"json3",this.cg),this.C||this.Mf||Uu(this)||this.player.YX("captionschanged",g.qL(this.K)));else{var l;this.B==="OFFLINE"?l=new tR(this.player,this.videoData,this.getAudioTrack()):this.B==="SABR_LIVE"?l=new xzs(this.videoData.G,this.player):this.B==="LIVE"?l=new SS(this.videoData.G,this.player):this.B==="INNERTUBE"?
l=new g.AK(this.player,this.videoData,this.getAudioTrack()):l=new g.mV(this.player,this.videoData.rY,this.videoData.videoId,g.Siv(this.videoData),this.videoData.Ru,this.videoData.eventId);this.G=l;g.Q(this,this.G);this.G.v2(this.cg)}};
g.C.unload=function(){this.C&&this.K?VIz(this,!1):(this.r9&&g.Or(this.r9),this.player.sX("captions"),this.II=[],this.G&&this.G.fI(),this.Qr.clear(),this.Kq&&this.player.v7(this.Kq),this.rH());g.IG.prototype.unload.call(this);this.player.RK();this.player.YX("captionschanged",{})};
g.C.create=function(){this.Ci()&&this.load();var l;a:{var y,r,c;if(this.GD.j("web_player_nitrate_promo_tooltip")&&((y=this.videoData.getPlayerResponse())==null?0:(r=y.captions)==null?0:(c=r.playerCaptionsTracklistRenderer)==null?0:c.enableTouchCaptionsNitrate)){var O,H;if(y=(l=this.videoData.getPlayerResponse())==null?void 0:(O=l.captions)==null?void 0:(H=O.playerCaptionsTracklistRenderer)==null?void 0:H.captionTracks)for(l=g.a(y),O=l.next();!O.done;O=l.next())if(O=O.value,O.kind==="asr"&&O.languageCode===
"en"){l=!0;break a}}l=!1}l&&this.V.publish("showpromotooltip",this.J.element)};
g.C.WA=function(){var l=BAH(this.player.getAudioTrack(),g.O8(this.GD));var y=l==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?RD(this,this.W):l==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&nE(this)?b0(this):cyx(this)||this.W||OPB(this)?RD(this,this.W):nE(this)?b0(this):null;if(this.C||this.Mf){var r=g.TB(this.G.K,!0);l=[];for(var c=0;c<r.length;c++){var O=r[c],H=g.rC("TRACK");H.setAttribute("kind","subtitles");H.setAttribute("label",g.YO(O));H.setAttribute("srclang",g.A1(O));H.setAttribute("id",O.toString());
this.Mf||H.setAttribute("src",this.G.bY(O,"vtt"));O===y&&H.setAttribute("default","1");l.push(H)}y=this.V.dX();y.Jh(l);l=y.Nh();this.w9&&this.Uz.S(l.textTracks,"change",this.Ha8)}else!this.K&&y&&jS(this,y),this.player.YX("onCaptionsTrackListChanged"),this.player.jt("onApiChange")};
g.C.Ha8=function(){for(var l=this.V.dX().Nh().textTracks,y=null,r=0;r<l.length;r++)if(l[r].mode==="showing")a:{y=g.TB(this.G.K,!0);for(var c=0;c<y.length;c++)if(y[c].toString()===l[r].id){y=y[c];break a}y=null}(this.loaded?this.K:null)!==y&&jS(this,y,!0)};
g.C.L5R=function(){!this.K&&this.C||this.unload()};
g.C.PW=function(l,y,r,c){if(l){var O;gKp(this,(O=this.K)!=null?O:void 0);this.G.vj()&&(this.II=[],this.V.sX("captions"),fE(this.Cq),this.Qr.reset());if(this.videoData.bR){var H;r=((H=r)!=null?H:0)+this.videoData.bR}l=this.Qr.MK(l,y,r,c);if(this.vT)for(y=g.a(l),r=y.next();!r.done;r=y.next())r=r.value,r.N=this.videoData.clientPlaybackNonce,r.vc=this.videoData.bR;y=!this.GD.j("html5_keep_caption_data_after_seek")&&(this.B==="LIVE"||this.B==="SABR_LIVE");this.player.v7(l,void 0,y);!this.W||this.Mf||Uu(this)||
g.Do(this.GD)||g.x8(this.GD)||g.bD(this.GD)||this.GD.Mf==="shortspage"||this.player.isInline()||(g.Or(this.r9),l=o_Q({Cb:0,e9:5,g7:5,XA:2,textAlign:0,z0:0,lang:"en"}),this.ZZ=[l],y=["Click "," for settings"],this.Y7||(r=new g.Mj(g.tI()),g.Q(this,r),this.Y7=r.element),r=l.end-l.start,(c=g.YO(this.K))&&this.ZZ.push(new qs(l.start,r,0,l.id,c)),this.ZZ.push(new qs(l.start,r,0,l.id,y[0]),new qs(l.start,r,0,l.id,this.Y7,!0),new qs(l.start,r,0,l.id,y[1],!0)),this.player.v7(this.ZZ),g.rD(this.r9));!this.W||
this.Mf||Uu(this)||(g.O8(this.GD)?zq(this,!0):kA(this,!0),this.X&&(this.X.B=this.K),this.player.RK());this.W=!1}};
g.C.onCueRangeEnter=function(l){this.II.push(l);fE(this.Cq)};
g.C.onCueRangeExit=function(l){g.jH(this.II,l);this.G instanceof SS&&this.G.J&&this.player.Pn([l]);fE(this.Cq)};
g.C.getCaptionWindowContainerId=function(){return this.J.element.id};
g.C.ajA=function(){F2x(this,this.ZZ);this.ZZ=null};
g.C.jX=function(){var l=this;if(!this.UF||!this.C){this.Cq.stop();g.iYz(this.Sj);this.II.sort(g.pf);var y=this.II;if(this.Kq){var r=g.FF(y,function(H){return this.Kq.indexOf(H)===-1},this);
r.length&&(y=r)}y=g.a(y);for(r=y.next();!r.done;r=y.next())fMJ(this,r.value);y=g.a(Object.entries(this.Nf));var c=y.next();for(r={};!c.done;r={lJ:void 0,w7:void 0},c=y.next()){var O=g.a(c.value);c=O.next().value;O=O.next().value;r.lJ=c;r.w7=O;this.Sj[r.lJ]?(r.w7.element.parentNode||(r.w7 instanceof wL||r.w7 instanceof D2||g.A6(this.Nf,function(H){return function(V,T){T!==H.lJ&&V.K.params.Cb===H.w7.K.params.Cb&&V.K.params.e9===H.w7.K.params.e9&&V.K.params.g7===H.w7.K.params.g7&&(V.dispose(),delete l.Nf[T]);
return T===H.lJ}}(r),this),this.J.element.appendChild(r.w7.element)),r.w7.Jr(this.Sj[r.lJ])):(r.w7.dispose(),delete this.Nf[r.lJ])}}};
g.C.ljw=function(){yyj(this,{},!0);this.player.YX("captionssettingschanged")};
g.C.hAf=function(){var l=LE.wX;l={background:l.background,backgroundOpacity:l.backgroundOpacity,charEdgeStyle:l.charEdgeStyle,color:l.color,fontFamily:l.fontFamily,fontSizeIncrement:l.fontSizeIncrement,fontStyle:l.bold&&l.italic?3:l.bold?1:l.italic?2:0,textOpacity:l.textOpacity,windowColor:LE.windowColor,windowOpacity:LE.windowOpacity};var y=xoJ()||{};y.background!=null&&(l.background=y.background);y.backgroundOverride!=null&&(l.backgroundOverride=y.backgroundOverride);y.backgroundOpacity!=null&&
(l.backgroundOpacity=y.backgroundOpacity);y.backgroundOpacityOverride!=null&&(l.backgroundOpacityOverride=y.backgroundOpacityOverride);y.charEdgeStyle!=null&&(l.charEdgeStyle=y.charEdgeStyle);y.charEdgeStyleOverride!=null&&(l.charEdgeStyleOverride=y.charEdgeStyleOverride);y.color!=null&&(l.color=y.color);y.colorOverride!=null&&(l.colorOverride=y.colorOverride);y.fontFamily!=null&&(l.fontFamily=y.fontFamily);y.fontFamilyOverride!=null&&(l.fontFamilyOverride=y.fontFamilyOverride);y.fontSizeIncrement!=
null&&(l.fontSizeIncrement=y.fontSizeIncrement);y.fontSizeIncrementOverride!=null&&(l.fontSizeIncrementOverride=y.fontSizeIncrementOverride);y.fontStyle!=null&&(l.fontStyle=y.fontStyle);y.fontStyleOverride!=null&&(l.fontStyleOverride=y.fontStyleOverride);y.textOpacity!=null&&(l.textOpacity=y.textOpacity);y.textOpacityOverride!=null&&(l.textOpacityOverride=y.textOpacityOverride);y.windowColor!=null&&(l.windowColor=y.windowColor);y.windowColorOverride!=null&&(l.windowColorOverride=y.windowColorOverride);
y.windowOpacity!=null&&(l.windowOpacity=y.windowOpacity);y.windowOpacityOverride!=null&&(l.windowOpacityOverride=y.windowOpacityOverride);return l};
g.C.QL=function(l,y){var r={};Object.assign(r,xoJ());Object.assign(r,l);yyj(this,r,y);this.player.YX("captionssettingschanged")};
g.C.rH=function(){!this.C&&this.loaded&&(g.KH(this.Nf,function(l,y){l.dispose();delete this.Nf[y]},this),this.jX())};
g.C.G0=function(l,y){switch(l){case "fontSize":if(isNaN(y))break;l=g.Sx(y,-2,4);this.QL({fontSizeIncrement:l});return l;case "reload":y&&!this.C&&jS(this,this.K,!0);break;case "stickyLoading":y!==void 0&&this.GD.J&&(g.O8(this.GD)?zq(this,!!y):kA(this,!!y));break;case "track":return SVJ(this,y);case "tracklist":return this.G?g.oJ(g.TB(this.G.K,!(!y||!y.includeAsr)),function(r){return g.qL(r)}):[];
case "translationLanguages":return this.G?this.G.C.map(function(r){return Object.assign({},r)}):[];
case "sampleSubtitles":this.C||y===void 0||pAp(this,!!y);break;case "sampleSubtitlesCustomized":this.C||pAp(this,!!y,y);break;case "recommendedTranslationLanguages":return g.z8();case "defaultTranslationSourceTrackIndices":return this.G?this.G.W:[]}};
g.C.getOptions=function(){var l="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.GD.J&&l.push("stickyLoading");return l};
g.C.At=function(){var l=this.K;if(this.V.Re("captions")){if(this.GD.j("html5_modify_caption_vss_logging")){var y;return(l=(y=this.videoData.M9)!=null?y:null)?{cc:g.G5v(l)}:{}}if(l)return y=l.vssId,l.translationLanguage&&y&&(y="t"+y+"."+g.A1(l)),{cc:y}}return{}};
g.C.b4q=function(){this.isSubtitlesOn()?(g.O8(this.GD)?zq(this,!1):kA(this,!1),gKp(this),jS(this,null,!0)):this.UY()};
g.C.UY=function(){var l=Uu(this)||!this.K?RD(this,!0):this.K;l&&this.a9(l.vssId,"m");this.isSubtitlesOn()||jS(this,Uu(this)||!this.K?RD(this,!0):this.K,!0)};
g.C.isSubtitlesOn=function(){return!!this.loaded&&!!this.K&&!Uu(this)};
g.C.pof=function(){var l=Uu(this);nE(this,l)?jS(this,this.getAudioTrack().G,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Hl()&&(this.W=!1,this.K=null,this.G&&(this.G.dispose(),this.G=null)),this.Ci()&&(l?jS(this,RD(this,!1),!1):this.load()))};
g.C.OQ=function(l){l&&(this.i8={top:l.top,right:l.right,bottom:l.bottom,left:l.left,width:1-l.left-l.right,height:1-l.top-l.bottom},this.J.element.style.top=this.i8.top*100+"%",this.J.element.style.left=this.i8.left*100+"%",this.J.element.style.width=this.i8.width*100+"%",this.J.element.style.height=this.i8.height*100+"%",this.J.element.style.position="absolute",l=NrQ(this))&&(this.J.element.style.width=l.width+"px",this.J.element.style.height=l.height+"px")};
g.C.onVideoDataChange=function(l,y){l==="newdata"&&(this.videoData=y,this.loaded&&this.unload(),this.W=!1,this.K=null,this.G&&(this.G.dispose(),this.G=null,this.player.YX("captionschanged",{})),this.Ci()&&this.load())};
g.C.getAudioTrack=function(){return this.vT&&this.player.getPresentingPlayerType()===2?this.videoData.jL:this.player.getAudioTrack()};
g.C.P2q=function(){var l=this.V.dX();l&&!l.Lq()&&l.TE();this.V.isFullscreen()?(this.C=this.qf=!0,this.loaded&&this.WA()):(this.qf=this.GD.controlsType==="3",this.C=lMH(this));jS(this,this.K)};
g.C.JW=function(){var l,y,r,c=(l=this.videoData.getPlayerResponse())==null?void 0:(y=l.captions)==null?void 0:(r=y.playerCaptionsTracklistRenderer)==null?void 0:r.openTranscriptCommand;c&&this.player.HT("innertubeCommand",c)};
g.C.nf=function(l,y,r){var c=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,O="";l&&(O=l.vssId,O=O.replace(c,""));var H="";l&&l.getId()&&(H=l.getId()||"");l&&l.getXtags()&&(l=l.getXtags(),l=l.replace(c,""),H=H.concat(";"+l));this.V.nf(y?O:"",y?H:"",r)};
g.C.a9=function(l,y){l=(l||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");l.length>0&&this.V.a9(l,y)};
g.C.D6=function(){this.G&&this.G.D6()};
g.tG.xo(eS,{jX:"smucd"});g.K8("captions",eS);})(_yt_player);
