(function(g){var window=this;'use strict';var nKb=function(l,y){l.HT("onAutonavCoundownStarted",y)},bPJ=function(l){var y,r,c;
return l==null?void 0:(y=l.playerOverlays)==null?void 0:(r=y.playerOverlayRenderer)==null?void 0:(c=r.autoplay)==null?void 0:c.playerOverlayAutoplayRenderer},gS=function(l,y,r){g.Er(l.element,"ytp-suggestion-set",!!y.videoId);
var c=y.playlistId;r=y.Ug(r?r:"mqdefault.jpg");var O=null,H=null;y instanceof g.Zs&&(y.lengthText?(O=y.lengthText||null,H=y.u4||null):y.lengthSeconds&&(O=g.Zb(y.lengthSeconds),H=g.Zb(y.lengthSeconds,!0)));var V=!!c;c=V&&g.h1(c).type==="RD";var T=y instanceof g.Zs?y.isLivePlayback:null,f=y instanceof g.Zs?y.isUpcoming:null,N=y.author,S=y.shortViewCount,F=y.publishedTimeText,p=[],E=[];N&&p.push(N);S&&(p.push(S),E.push(S));F&&E.push(F);r={title:y.title,author:N,author_and_views:p.join(" \u2022 "),aria_label:y.ariaLabel||
g.mn("Watch $TITLE",{TITLE:y.title}),duration:O,timestamp:H,url:y.S5(),is_live:T,is_upcoming:f,is_list:V,is_mix:c,background:r?"background-image: url("+r+")":"",views_and_publish_time:E.join(" \u2022 "),autoplayAlternativeHeader:y.S7};y instanceof g.G2&&(r.playlist_length=y.playlistLength);l.update(r)},Tt=function(l){var y=l.D(),r=y.B;
g.n.call(this,{U:"a",Z:"ytp-autonav-suggestion-card",Y:{href:"{{url}}",target:r?y.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},T:[{U:"div",RI:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Y:{style:"{{background}}"},T:[{U:"div",Y:{"aria-label":"{{timestamp}}"},RI:["ytp-autonav-timestamp"],b8:"{{duration}}"},{U:"div",RI:["ytp-autonav-live-stamp"],b8:"Live"},{U:"div",
RI:["ytp-autonav-upcoming-stamp"],b8:"Upcoming"},{U:"div",Z:"ytp-autonav-list-overlay",T:[{U:"div",Z:"ytp-autonav-mix-text",b8:"Mix"},{U:"div",Z:"ytp-autonav-mix-icon"}]}]},{U:"div",RI:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],b8:"{{title}}"},{U:"div",RI:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],b8:"{{author}}"},{U:"div",RI:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],b8:"{{views_and_publish_time}}"}]});this.V=l;this.suggestion=
null;this.G=r;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},fB=function(l,y){y=y===void 0?!1:y;
g.n.call(this,{U:"div",Z:"ytp-autonav-endscreen-countdown-overlay"});var r=this;this.J=y;this.cancelCommand=this.L=void 0;this.N=0;this.container=new g.n({U:"div",Z:"ytp-autonav-endscreen-countdown-container"});g.Q(this,this.container);this.container.k7(this.element);y=l.D();var c=y.B;this.V=l;this.suggestion=null;this.onVideoDataChange("newdata",this.V.getVideoData());this.S(l,"videodatachange",this.onVideoDataChange);this.G=new g.n({U:"div",Z:"ytp-autonav-endscreen-upnext-container",Y:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},T:[{U:"div",Z:"ytp-autonav-endscreen-upnext-header"},{U:"div",Z:"ytp-autonav-endscreen-upnext-alternative-header",b8:"{{autoplayAlternativeHeader}}"},{U:"a",Z:"ytp-autonav-endscreen-link-container",Y:{href:"{{url}}",target:c?y.X:""},T:[{U:"div",Z:"ytp-autonav-endscreen-upnext-thumbnail",Y:{style:"{{background}}"},T:[{U:"div",Y:{"aria-label":"{{timestamp}}"},RI:["ytp-autonav-timestamp"],
b8:"{{duration}}"},{U:"div",RI:["ytp-autonav-live-stamp"],b8:"Live"},{U:"div",RI:["ytp-autonav-upcoming-stamp"],b8:"Upcoming"}]},{U:"div",Z:"ytp-autonav-endscreen-video-info",T:[{U:"div",Z:"ytp-autonav-endscreen-premium-badge"},{U:"div",Z:"ytp-autonav-endscreen-upnext-title",b8:"{{title}}"},{U:"div",Z:"ytp-autonav-endscreen-upnext-author",b8:"{{author}}"},{U:"div",Z:"ytp-autonav-view-and-date",b8:"{{views_and_publish_time}}"},{U:"div",Z:"ytp-autonav-author-and-view",b8:"{{author_and_views}}"}]}]}]});
g.Q(this,this.G);this.G.k7(this.container.element);c||this.S(this.G.BT("ytp-autonav-endscreen-link-container"),"click",this.XB);this.V.createClientVe(this.container.element,this,115127);this.V.createClientVe(this.G.BT("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.n({U:"div",Z:"ytp-autonav-overlay"});g.Q(this,this.overlay);this.overlay.k7(this.container.element);this.K=new g.n({U:"div",Z:"ytp-autonav-endscreen-button-container"});g.Q(this,this.K);this.K.k7(this.container.element);
this.cancelButton=new g.n({U:"button",RI:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",y.j("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{"aria-label":"Cancel autoplay"},b8:"Cancel"});g.Q(this,this.cancelButton);this.cancelButton.k7(this.K.element);this.cancelButton.listen("click",this.h5,this);this.V.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.n({U:"a",RI:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
y.j("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{href:"{{url}}",role:"button","aria-label":"Play next video"},b8:"Play Now"});g.Q(this,this.playButton);this.playButton.k7(this.K.element);this.playButton.listen("click",this.XB,this);this.V.createServerVe(this.playButton.element,this.playButton,!0);(y=this.V.getVideoData())&&RGH(this,y);this.B=new g.yU(function(){UiI(r)},500);
g.Q(this,this.B);this.Pw();this.S(l,"autonavvisibility",this.Pw);this.V.j("web_autonav_color_transition")&&(this.S(l,"autonavchange",this.nF),this.S(l,"onAutonavCoundownStarted",this.Baf))},NV=function(l){var y=l.V.DO(!0,l.V.isFullscreen());
g.Er(l.container.element,"ytp-autonav-endscreen-small-mode",l.wJ(y));g.Er(l.container.element,"ytp-autonav-endscreen-is-premium",!!l.suggestion&&!!l.suggestion.fMZ);g.Er(l.V.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!l.V.TA());g.Er(l.V.getRootNode(),"countdown-running",l.qV());g.Er(l.container.element,"ytp-player-content",l.V.TA());g.ET(l.overlay.element,{width:y.width+"px"});if(!l.qV()){l.V.TA()?zGx(l,Math.round(k1g(l)/1E3)):zGx(l);y=!!l.suggestion&&!!l.suggestion.S7;var r=l.V.TA()||
!y;g.Er(l.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!r&&y);g.Er(l.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",r&&!y);l.K.YN(l.V.TA());g.Er(l.element,"ytp-enable-w2w-color-transitions",jLz(l))}},UiI=function(l){var y=k1g(l),r=Math,c=r.min;
var O=l.N?Date.now()-l.N:0;r=c.call(r,O,y);zGx(l,Math.ceil((y-r)/1E3));y-r<=500&&l.qV()?l.select(!0):l.qV()&&l.B.start()},k1g=function(l){if(l.V.isFullscreen()){var y;
l=(y=l.V.getVideoData())==null?void 0:y.KC;return l===-1||l===void 0?8E3:l}return l.V.Xc()>=0?l.V.Xc():g.Ib(l.V.D().experiments,"autoplay_time")||1E4},RGH=function(l,y){y=y.getWatchNextResponse();
var r,c;y=(r=bPJ(y))==null?void 0:(c=r.nextButton)==null?void 0:c.buttonRenderer;l.L=y==null?void 0:y.navigationEndpoint;r=y==null?void 0:y.trackingParams;l.playButton&&r&&l.V.setTrackingParams(l.playButton.element,r)},jLz=function(l){var y;
return!((y=l.V.getVideoData())==null||!y.watchToWatchTransitionRenderer)},zGx=function(l,y){y=y===void 0?-1:y;
l=l.G.BT("ytp-autonav-endscreen-upnext-header");g.H7(l);if(y>=0){y=String(y);var r="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],c="Up next in $SECONDS".indexOf(r);if(c>=0){l.appendChild(g.c7("Up next in $SECONDS".slice(0,c)));var O=g.rC("span");g.TH(O,"ytp-autonav-endscreen-upnext-header-countdown-number");g.To(O,y);l.appendChild(O);l.appendChild(g.c7("Up next in $SECONDS".slice(c+r.length)));return}}g.To(l,"Up next")},SQ=function(l,y){g.n.call(this,{U:"div",
RI:["html5-endscreen","ytp-player-content",y||"base-endscreen"]});this.created=!1;this.player=l},Fy=function(l){g.n.call(this,{U:"div",
RI:["ytp-upnext","ytp-player-content"],Y:{"aria-label":"{{aria_label}}"},T:[{U:"div",Z:"ytp-cued-thumbnail-overlay-image",Y:{style:"{{background}}"}},{U:"span",Z:"ytp-upnext-top",T:[{U:"span",Z:"ytp-upnext-header",b8:"Up Next"},{U:"span",Z:"ytp-upnext-title",b8:"{{title}}"},{U:"span",Z:"ytp-upnext-author",b8:"{{author}}"}]},{U:"a",Z:"ytp-upnext-autoplay-icon",Y:{role:"button",href:"{{url}}","aria-label":"Play next video"},T:[{U:"svg",Y:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
T:[{U:"circle",Z:"ytp-svg-autoplay-circle",Y:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{U:"circle",Z:"ytp-svg-autoplay-ring",Y:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{U:"path",Z:"ytp-svg-fill",Y:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{U:"span",Z:"ytp-upnext-bottom",T:[{U:"span",Z:"ytp-upnext-cancel"},{U:"span",Z:"ytp-upnext-paused",
b8:"Autoplay is paused"}]}]});this.api=l;this.cancelButton=null;this.L=this.BT("ytp-svg-autoplay-ring");this.N=this.notification=this.G=this.suggestion=null;this.B=new g.yU(this.cD,5E3,this);this.K=0;var y=this.BT("ytp-upnext-cancel");this.cancelButton=new g.n({U:"button",RI:["ytp-upnext-cancel-button","ytp-button"],Y:{tabindex:"0","aria-label":"Cancel autoplay"},b8:"Cancel"});g.Q(this,this.cancelButton);this.cancelButton.listen("click",this.A5,this);this.cancelButton.k7(y);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.Q(this,this.B);this.api.createClientVe(this.element,this,18788);y=this.BT("ytp-upnext-autoplay-icon");this.S(y,"click",this.KF);this.api.createClientVe(y,this,115130);this.wH();this.S(l,"autonavvisibility",this.wH);this.S(l,"mdxnowautoplaying",this.wo9);this.S(l,"mdxautoplaycanceled",this.Gkf);g.Er(this.element,"ytp-upnext-mobile",this.api.D().K)},L2J=function(l,y){if(y)return y;
if(l.api.isFullscreen()){var r;l=(r=l.api.getVideoData())==null?void 0:r.KC;return l===-1||l===void 0?8E3:l}return l.api.Xc()>=0?l.api.Xc():g.Ib(l.api.D().experiments,"autoplay_time")||1E4},lhs=function(l,y){y=L2J(l,y);
var r=Math,c=r.min;var O=(0,g.$$)()-l.K;r=c.call(r,O,y);y=y===0?1:Math.min(r/y,1);l.L.setAttribute("stroke-dashoffset",""+-211*(y+1));y>=1&&l.qV()&&l.api.getPresentingPlayerType()!==3?l.select(!0):l.qV()&&l.G.start()},pB=function(l){SQ.call(this,l,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.n({U:"div",Z:"ytp-suggestion-panel",T:[{U:"div",RI:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],b8:"More videos"}]});this.W=new g.n({U:"div",Z:"ytp-suggestions-container"});this.videos=[];this.N=null;this.L=this.J=!1;this.K=new fB(this.player);g.Q(this,this.K);this.K.k7(this.element);l.getVideoData().Qk?this.G=this.K:(this.G=new Fy(l),g.wQ(this.player,this.G.element,4),g.Q(this,this.G));this.overlay=new g.n({U:"div",
Z:"ytp-autonav-overlay-cancelled-state"});g.Q(this,this.overlay);this.overlay.k7(this.element);this.B=new g.n4(this);g.Q(this,this.B);g.Q(this,this.table);this.table.k7(this.element);this.table.show();g.Q(this,this.W);this.W.k7(this.table.element);this.hide()},EW=function(l){var y=l.TA();
y!==l.L&&(l.L=y,l.player.publish("autonavvisibility"),l.L?(l.K!==l.G&&l.K.hide(),l.table.hide()):(l.K!==l.G&&l.K.show(),l.table.show()))},uP=function(l,y){g.n.call(this,{U:"button",
RI:["ytp-watch-on-youtube-button","ytp-button"],b8:"{{content}}"});this.V=l;this.buttonType=this.buttonType=y;this.fn();this.buttonType===2&&g.Nr(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.fn);this.YN(!0)},MV=function(l,y){SQ.call(this,l,"embeds-lite-endscreen");
this.V=l;this.G=y;this.V.createClientVe(this.element,this,156943);this.watchButton=new uP(l,2);g.Q(this,this.watchButton);this.watchButton.k7(this.element);this.hide()},yvJ=function(l){SQ.call(this,l,"subscribecard-endscreen");
this.G=new g.n({U:"div",Z:"ytp-subscribe-card",T:[{U:"img",Z:"ytp-author-image",Y:{src:"{{profilePicture}}"}},{U:"div",Z:"ytp-subscribe-card-right",T:[{U:"div",Z:"ytp-author-name",b8:"{{author}}"},{U:"div",Z:"html5-subscribe-button-container"}]}]});g.Q(this,this.G);this.G.k7(this.element);var y=l.getVideoData();this.subscribeButton=new g.yh("Subscribe",null,"Unsubscribe",null,!0,!1,y.dl,y.subscribed,"trailer-endscreen",null,l,!1);g.Q(this,this.subscribeButton);this.subscribeButton.k7(this.G.BT("html5-subscribe-button-container"));
this.S(l,"videodatachange",this.ej);this.ej();this.hide()},aa=function(l){var y=l.D(),r=g.wg||g.Bp?{style:"will-change: opacity"}:void 0,c=y.B,O=["ytp-videowall-still"];
y.K&&O.push("ytp-videowall-show-text");g.n.call(this,{U:"a",RI:O,Y:{href:"{{url}}",target:c?y.X:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},T:[{U:"div",Z:"ytp-videowall-still-image",Y:{style:"{{background}}"}},{U:"span",Z:"ytp-videowall-still-info",Y:{"aria-hidden":"true"},T:[{U:"span",Z:"ytp-videowall-still-info-bg",T:[{U:"span",Z:"ytp-videowall-still-info-content",Y:r,T:[{U:"span",Z:"ytp-videowall-still-info-title",b8:"{{title}}"},
{U:"span",Z:"ytp-videowall-still-info-author",b8:"{{author_and_views}}"},{U:"span",Z:"ytp-videowall-still-info-live",b8:"Live"},{U:"span",Z:"ytp-videowall-still-info-duration",b8:"{{duration}}"}]}]}]},{U:"span",RI:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},T:[{U:"span",Z:"ytp-videowall-still-listlabel-icon"},"Playlist",{U:"span",Z:"ytp-videowall-still-listlabel-length",T:[" (",{U:"span",b8:"{{playlist_length}}"},")"]}]},{U:"span",RI:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},T:[{U:"span",Z:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{U:"span",Z:"ytp-videowall-still-listlabel-length",b8:" (50+)"}]}]});this.suggestion=null;this.K=c;this.api=l;this.G=new g.n4(this);g.Q(this,this.G);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.G.S(l,"videodatachange",this.onVideoDataChange);l.createServerVe(this.element,this);this.onVideoDataChange()},sW=function(l){SQ.call(this,l,"videowall-endscreen");
var y=this;this.V=l;this.N=0;this.stills=[];this.B=this.videoData=null;this.L=this.W=!1;this.X=null;this.K=new g.n4(this);g.Q(this,this.K);this.J=new g.yU(function(){g.Nr(y.element,"ytp-show-tiles")},0);
g.Q(this,this.J);var r=new g.n({U:"button",RI:["ytp-button","ytp-endscreen-previous"],Y:{"aria-label":"Previous"},T:[g.mI()]});g.Q(this,r);r.k7(this.element);r.listen("click",this.by,this);this.table=new g.Mj({U:"div",Z:"ytp-endscreen-content"});g.Q(this,this.table);this.table.k7(this.element);r=new g.n({U:"button",RI:["ytp-button","ytp-endscreen-next"],Y:{"aria-label":"Next"},T:[g.vb()]});g.Q(this,r);r.k7(this.element);r.listen("click",this.yd,this);l.getVideoData().Qk?this.G=new fB(l,!0):this.G=
new Fy(l);g.Q(this,this.G);g.wQ(this.player,this.G.element,4);l.createClientVe(this.element,this,158789);this.hide()},KB=function(l){return g.PZ(l.player)&&l.Wy()&&!l.B},Ia=function(l){var y=l.TA();
y!==l.W&&(l.W=y,l.player.publish("autonavvisibility"))},Yp=function(l){SQ.call(this,l,"watch-again-on-youtube-endscreen");
this.watchButton=new uP(l,1);g.Q(this,this.watchButton);this.watchButton.k7(this.element);g.LPz(l)&&(this.G=new g.kV(l),g.Q(this,this.G),this.K=new g.n({U:"div",RI:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Y:{tabIndex:"-1"},T:[this.G]}),g.Q(this,this.K),this.G.k7(this.K.element),this.K.k7(this.element));l.createClientVe(this.element,this,156914);this.hide()},Hns=function(l){g.IG.call(this,l);
var y=this;this.endScreen=null;this.K=this.G=this.N=this.B=!1;this.listeners=new g.n4(this);g.Q(this,this.listeners);var r=l.D(),c=l.getVideoData();c=c&&c.limitedPlaybackDurationInSeconds!==0;g.um(g.nq(r))&&c&&!g.dQ(l)?(this.K=!0,this.endScreen=new MV(l,g.qE(l))):l.isEmbedsShortsMode()?this.endScreen=new Yp(l):rvQ(l)?(this.B=!0,cvQ(this),this.G?this.endScreen=new pB(l):this.endScreen=new sW(l)):r.Qk?this.endScreen=new yvJ(l):this.endScreen=new SQ(l);g.Q(this,this.endScreen);g.wQ(l,this.endScreen.element,
4);Onp(this);this.listeners.S(l,"videodatachange",this.onVideoDataChange,this);this.listeners.S(l,g.Eg("endscreen"),function(O){y.onCueRangeEnter(O)});
this.listeners.S(l,g.uw("endscreen"),function(O){y.onCueRangeExit(O)})},cvQ=function(l){var y=l.player.getVideoData();
if(!y||l.G===y.UE&&l.N===y.Qk)return!1;l.G=y.UE;l.N=y.Qk;return!0},rvQ=function(l){l=l.D();
return l.Jd&&!l.Qk&&!l.disableOrganicUi},Onp=function(l){l.player.sX("endscreen");
var y=l.player.getVideoData();y=new g.F8(Math.max((y.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var r=new g.F8(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});l.player.v7([y,r])};
g.$h.prototype.Xc=g.cz(14,function(){return this.app.Xc()});
g.af.prototype.Xc=g.cz(13,function(){return this.getVideoData().q0});
g.o9.prototype.AS=g.cz(12,function(l){this.f4().AS(l)});
g.au.prototype.AS=g.cz(11,function(l){this.G!==l&&(this.G=l,this.ej())});
g.hG.prototype.AS=g.cz(10,function(l){this.overflowButton&&this.overflowButton.AS(l)});
g.o9.prototype.Ks=g.cz(9,function(l){this.f4().Ks(l)});
g.qH.prototype.Ks=g.cz(8,function(l){this.K!==l&&(this.K=l,this.ej())});
g.hG.prototype.Ks=g.cz(7,function(l){this.shareButton&&this.shareButton.Ks(l)});
g.o9.prototype.oR=g.cz(6,function(l){this.f4().oR(l)});
g.RG.prototype.oR=g.cz(5,function(l){this.eI!==l&&(this.eI=l,this.LQ())});
g.o9.prototype.IR=g.cz(4,function(l){this.f4().IR(l)});
g.hG.prototype.IR=g.cz(3,function(l){this.JA!==l&&(this.JA=l,this.Rc())});g.M(Tt,g.n);Tt.prototype.select=function(){this.V.FS(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.E4||void 0)&&this.V.logClick(this.element)};
Tt.prototype.onClick=function(l){g.FO(l,this.V,this.G,this.suggestion.sessionData||void 0)&&this.select()};
Tt.prototype.onKeyPress=function(l){switch(l.keyCode){case 13:case 32:l.defaultPrevented||(this.select(),l.preventDefault())}};g.M(fB,g.n);g.C=fB.prototype;g.C.N_=function(l){this.suggestion!==l&&(this.suggestion=l,gS(this.G,l),this.playButton.updateValue("url",this.suggestion.S5()),NV(this))};
g.C.qV=function(){return this.N>0};
g.C.Qa=function(){this.qV()||(this.N=Date.now(),UiI(this),nKb(this.V,k1g(this)),g.Er(this.V.getRootNode(),"countdown-running",this.qV()))};
g.C.CM=function(){this.dE();UiI(this);var l=this.G.BT("ytp-autonav-endscreen-upnext-header");l&&g.To(l,"Up next")};
g.C.dE=function(){this.qV()&&(this.B.stop(),this.N=0)};
g.C.select=function(l){this.V.nextVideo(!1,l===void 0?!1:l);this.dE()};
g.C.XB=function(l){g.FO(l,this.V)&&(l.currentTarget===this.playButton.element?this.V.logClick(this.playButton.element):l.currentTarget===this.G.BT("ytp-autonav-endscreen-link-container")&&(l=this.G.BT("ytp-autonav-endscreen-link-container"),this.V.logVisibility(l,!0),this.V.logClick(l)),this.L?(this.V.HT("innertubeCommand",this.L),this.dE()):this.select())};
g.C.h5=function(){this.V.logClick(this.cancelButton.element);g.tt(this.V,!0);this.cancelCommand&&this.V.HT("innertubeCommand",this.cancelCommand)};
g.C.onVideoDataChange=function(l,y){RGH(this,y);l=y.getWatchNextResponse();var r,c;l=(r=bPJ(l))==null?void 0:(c=r.cancelButton)==null?void 0:c.buttonRenderer;this.cancelCommand=l==null?void 0:l.command};
g.C.Baf=function(l){if(jLz(this)){var y=this.V.getVideoData().watchToWatchTransitionRenderer,r=y==null?void 0:y.fromColorPaletteDark;y=y==null?void 0:y.toColorPaletteDark;if(r&&y){var c=this.element;c.style.setProperty("--w2w-start-background-color",g.Uv(r.surgeColor));c.style.setProperty("--w2w-start-primary-text-color",g.Uv(r.primaryTitleColor));c.style.setProperty("--w2w-start-secondary-text-color",g.Uv(r.secondaryTitleColor));c.style.setProperty("--w2w-end-background-color",g.Uv(y.surgeColor));
c.style.setProperty("--w2w-end-primary-text-color",g.Uv(y.primaryTitleColor));c.style.setProperty("--w2w-end-secondary-text-color",g.Uv(y.secondaryTitleColor));c.style.setProperty("--w2w-animation-duration",l+"ms")}g.Er(this.element,"ytp-w2w-animate",!0)}};
g.C.nF=function(l){this.V.j("web_autonav_color_transition")&&l!==2&&g.Er(this.element,"ytp-w2w-animate",!1)};
g.C.Pw=function(){var l=this.V.TA();this.J&&this.OF!==l&&this.YN(l);NV(this);this.V.logVisibility(this.container.element,l);this.V.logVisibility(this.cancelButton.element,l);this.V.logVisibility(this.G.BT("ytp-autonav-endscreen-link-container"),l);this.V.logVisibility(this.playButton.element,l)};
g.C.wJ=function(l){return l.width<400||l.height<459};g.M(SQ,g.n);g.C=SQ.prototype;g.C.create=function(){this.created=!0};
g.C.destroy=function(){this.created=!1};
g.C.Wy=function(){return!1};
g.C.TA=function(){return!1};
g.C.NL=function(){return!1};g.M(Fy,g.n);g.C=Fy.prototype;g.C.cD=function(){this.notification&&(this.B.stop(),this.Ns(this.N),this.N=null,this.notification.close(),this.notification=null)};
g.C.N_=function(l){this.suggestion=l;gS(this,l,"hqdefault.jpg")};
g.C.wH=function(){this.YN(this.api.TA());this.api.logVisibility(this.element,this.api.TA());this.api.logVisibility(this.BT("ytp-upnext-autoplay-icon"),this.api.TA());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.TA())};
g.C.yk9=function(){window.focus();this.cD()};
g.C.Qa=function(l){var y=this;this.qV()||(g.Fz("a11y-announce","Up Next "+this.suggestion.title),this.K=(0,g.$$)(),this.G=new g.yU(function(){lhs(y,l)},25),lhs(this,l),nKb(this.api,L2J(this,l)));
g.Fb(this.element,"ytp-upnext-autoplay-paused")};
g.C.hide=function(){g.n.prototype.hide.call(this)};
g.C.qV=function(){return!!this.G};
g.C.CM=function(){this.dE();this.K=(0,g.$$)();lhs(this);g.Nr(this.element,"ytp-upnext-autoplay-paused")};
g.C.dE=function(){this.qV()&&(this.G.dispose(),this.G=null)};
g.C.select=function(l){l=l===void 0?!1:l;if(this.api.D().j("autonav_notifications")&&l&&window.Notification&&typeof document.hasFocus==="function"){var y=Notification.permission;y==="default"?Notification.requestPermission():y!=="granted"||document.hasFocus()||(this.cD(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Ug()}),this.N=this.S(this.notification,"click",this.yk9),this.B.start())}this.dE();this.api.nextVideo(!1,l)};
g.C.KF=function(l){!g.gC(this.cancelButton.element,l.target)&&g.FO(l,this.api)&&(this.api.TA()&&this.api.logClick(this.BT("ytp-upnext-autoplay-icon")),this.select())};
g.C.A5=function(){this.api.TA()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.tt(this.api,!0)};
g.C.wo9=function(l){this.api.getPresentingPlayerType();this.show();this.Qa(l)};
g.C.Gkf=function(){this.api.getPresentingPlayerType();this.dE();this.hide()};
g.C.yr=function(){this.dE();this.cD();g.n.prototype.yr.call(this)};g.M(pB,SQ);g.C=pB.prototype;g.C.create=function(){SQ.prototype.create.call(this);this.B.S(this.player,"appresize",this.jB);this.B.S(this.player,"onVideoAreaChange",this.jB);this.B.S(this.player,"videodatachange",this.onVideoDataChange);this.B.S(this.player,"autonavchange",this.G3);this.B.S(this.player,"onAutonavCancelled",this.iy);this.onVideoDataChange()};
g.C.show=function(){SQ.prototype.show.call(this);(this.J||this.N&&this.N!==this.videoData.clientPlaybackNonce)&&g.tt(this.player,!1);g.PZ(this.player)&&this.Wy()&&!this.N?(EW(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.G.select(!0):this.G.Qa():this.videoData.autonavState===3&&this.G.CM()):(g.tt(this.player,!0),EW(this));this.jB()};
g.C.hide=function(){SQ.prototype.hide.call(this);this.G.CM();EW(this)};
g.C.jB=function(){var l=this.player.DO(!0,this.player.isFullscreen());EW(this);NV(this.K);g.Er(this.element,"ytp-autonav-cancelled-small-mode",this.wJ(l));g.Er(this.element,"ytp-autonav-cancelled-tiny-mode",this.mU(l));g.Er(this.element,"ytp-autonav-cancelled-mini-mode",l.width<=400||l.height<=360);this.overlay&&g.ET(this.overlay.element,{width:l.width+"px"});if(!this.L)for(l=0;l<this.videos.length;l++)g.Er(this.videos[l].element,"ytp-suggestion-card-with-margin",l%2===1)};
g.C.onVideoDataChange=function(){var l=this.player.getVideoData();if(this.videoData!==l&&l){this.videoData=l;if((l=this.videoData.suggestions)&&l.length||this.player.j("web_player_autonav_empty_suggestions_fix")){var y=g.Ce(this.videoData);y&&(this.G.N_(y),this.G!==this.K&&this.K.N_(y))}if(l&&l.length)for(y=0;y<VJb.length;++y){var r=VJb[y];if(l&&l[r]){this.videos[y]=new Tt(this.player);var c=this.videos[y];r=l[r];c.suggestion!==r&&(c.suggestion=r,gS(c,r));g.Q(this,this.videos[y]);this.videos[y].k7(this.W.element)}}this.jB()}};
g.C.G3=function(l){l===1?(this.J=!1,this.N=this.videoData.clientPlaybackNonce,this.G.dE(),this.OF&&this.jB()):(this.J=!0,this.TA()&&(l===2?this.G.Qa():l===3&&this.G.CM()))};
g.C.iy=function(l){l?this.G3(1):(this.N=null,this.J=!1)};
g.C.Wy=function(){return this.videoData.autonavState!==1};
g.C.wJ=function(l){return(l.width<910||l.height<459)&&!this.mU(l)&&!(l.width<=400||l.height<=360)};
g.C.mU=function(l){return l.width<800&&!(l.width<=400||l.height<=360)};
g.C.TA=function(){return this.OF&&g.PZ(this.player)&&this.Wy()&&!this.N};
var VJb=[1,3,2,4];g.M(uP,g.n);g.C=uP.prototype;g.C.fn=function(){switch(this.buttonType){case 1:var l="Watch again on YouTube";var y=156915;break;case 2:l="Continue watching on YouTube";y=156942;break;default:l="Continue watching on YouTube",y=156942}this.update({content:l});this.V.hasVe(this.element)&&this.V.destroyVe(this.element);this.V.createClientVe(this.element,this,y)};
g.C.onClick=function(l){this.V.j("web_player_log_click_before_generating_ve_conversion_params")&&this.V.logClick(this.element);g.pI(this.getVideoUrl(),this.V,l);this.V.j("web_player_log_click_before_generating_ve_conversion_params")||this.V.logClick(this.element)};
g.C.getVideoUrl=function(){var l=!0;switch(this.buttonType){case 1:l=!0;break;case 2:l=!1}l=this.V.getVideoUrl(l,!1,!1,!0);var y=this.V.D();if(g.DY(y)){var r={};g.DY(y)&&g.a9(this.V,"addEmbedsConversionTrackingParams",[r]);l=g.bd(l,r)}return l};
g.C.logVisibility=function(){this.V.logVisibility(this.element,this.OF&&this.C)};
g.C.show=function(){g.n.prototype.show.call(this);this.logVisibility()};
g.C.hide=function(){g.n.prototype.hide.call(this);this.logVisibility()};
g.C.JD=function(l){g.n.prototype.JD.call(this,l);this.logVisibility()};g.M(MV,SQ);MV.prototype.show=function(){this.player.getPlayerState()!==3&&(SQ.prototype.show.call(this),this.G.IR(!0),this.G.Ks(!0),this.V.D().zA||this.G.AS(!0),this.V.logVisibility(this.element,!0),this.watchButton.JD(!0))};
MV.prototype.hide=function(){SQ.prototype.hide.call(this);this.G.IR(!1);this.G.Ks(!1);this.G.AS(!1);this.V.logVisibility(this.element,!1);this.watchButton.JD(!1)};g.M(yvJ,SQ);yvJ.prototype.ej=function(){var l=this.player.getVideoData();this.G.update({profilePicture:l.profilePicture,author:l.author});this.subscribeButton.channelId=l.dl;var y=this.subscribeButton;l.subscribed?y.G():y.K()};g.M(aa,g.n);aa.prototype.select=function(){this.api.FS(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.E4||void 0)&&this.api.logClick(this.element)};
aa.prototype.onClick=function(l){if(g.DY(this.api.D())&&this.api.j("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var y=this.suggestion.S5(),r={};g.i7(this.api,r);y=g.bd(y,r);g.pI(y,this.api,l)}else g.FO(l,this.api,this.K,this.suggestion.sessionData||void 0)&&this.select()};
aa.prototype.onKeyPress=function(l){switch(l.keyCode){case 13:case 32:l.defaultPrevented||(this.select(),l.preventDefault())}};
aa.prototype.onVideoDataChange=function(){var l=this.api.getVideoData(),y=this.api.D();this.K=l.Yl?!1:y.B};g.M(sW,SQ);g.C=sW.prototype;g.C.create=function(){SQ.prototype.create.call(this);var l=this.player.getVideoData();l&&(this.videoData=l);this.Sp();this.K.S(this.player,"appresize",this.Sp);this.K.S(this.player,"onVideoAreaChange",this.Sp);this.K.S(this.player,"videodatachange",this.onVideoDataChange);this.K.S(this.player,"autonavchange",this.Zz);this.K.S(this.player,"onAutonavCancelled",this.OJ);l=this.videoData.autonavState;l!==this.X&&this.Zz(l);this.K.S(this.element,"transitionend",this.ttz)};
g.C.destroy=function(){g.tC(this.K);g.Tj(this.stills);this.stills=[];SQ.prototype.destroy.call(this);g.Fb(this.element,"ytp-show-tiles");this.J.stop();this.X=this.videoData.autonavState};
g.C.Wy=function(){return this.videoData.autonavState!==1};
g.C.show=function(){var l=this.OF;SQ.prototype.show.call(this);g.Fb(this.element,"ytp-show-tiles");this.player.D().K?g.c6(this.J):this.J.start();(this.L||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.tt(this.player,!1);KB(this)?(Ia(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.G.select(!0):this.G.Qa():this.videoData.autonavState===3&&this.G.CM()):(g.tt(this.player,!0),Ia(this));l!==this.OF&&this.player.logVisibility(this.element,!0)};
g.C.hide=function(){var l=this.OF;SQ.prototype.hide.call(this);this.G.CM();Ia(this);l!==this.OF&&this.player.logVisibility(this.element,!1)};
g.C.ttz=function(l){l.target===this.element&&this.Sp()};
g.C.Sp=function(){var l,y,r,c;var O=((l=this.videoData)==null?0:(y=l.suggestions)==null?0:y.length)?(r=this.videoData)==null?void 0:r.suggestions:[(c=this.videoData)==null?void 0:g.Ce(c)];if(O.length){g.Nr(this.element,"ytp-endscreen-paginate");var H=this.V.DO(!0,this.V.isFullscreen());if(l=g.qE(this.V))l=l.DM()?48:32,H.width-=l*2;var V=H.width/H.height;c=96/54;y=l=2;var T=Math.max(H.width/96,2),f=Math.max(H.height/54,2);r=O.length;var N=r*4;for(N-=4;N>0&&(l<T||y<f);){var S=l/2,F=y/2,p=l<=T-2&&N>=
F*4,E=y<=f-2&&N>=S*4;if((S+1)/F*c/V>V/(S/(F+1)*c)&&E)N-=S*4,y+=2;else if(p)N-=F*4,l+=2;else if(E)N-=S*4,y+=2;else break}c=!1;N>=12&&r*4-N<=6&&(y>=4||l>=4)&&(c=!0);N=l*96;T=y*54;V=N/T<V?H.height/T:H.width/N;V=Math.min(V,2);N=Math.floor(Math.min(H.width,N*V));T=Math.floor(Math.min(H.height,T*V));H=this.table.element;H.ariaLive="polite";g.oA(H,N,T);g.ET(H,{marginLeft:N/-2+"px",marginTop:T/-2+"px"});this.G.N_(g.Ce(this.videoData));this.G instanceof fB&&NV(this.G);g.Er(this.element,"ytp-endscreen-takeover",
KB(this));Ia(this);N+=4;T+=4;V=0;H.ariaBusy="true";for(f=0;f<l;f++)for(S=0;S<y;S++)if(F=V,E=0,c&&f>=l-2&&S>=y-2?E=1:S%2===0&&f%2===0&&(S<2&&f<2?S===0&&f===0&&(E=2):E=2),F=g.F_(F+this.N,r),E!==0){p=this.stills[V];p||(p=new aa(this.player),this.stills[V]=p,H.appendChild(p.element));var u=Math.floor(T*S/y),I=Math.floor(N*f/l),q=Math.floor(T*(S+E)/y)-u-4,W=Math.floor(N*(f+E)/l)-I-4;g.IA(p.element,I,u);g.oA(p.element,W,q);g.ET(p.element,"transitionDelay",(S+f)/20+"s");g.Er(p.element,"ytp-videowall-still-mini",
E===1);g.Er(p.element,"ytp-videowall-still-large",E>2);E=Math.max(W,q);g.Er(p.element,"ytp-videowall-still-round-large",E>=256);g.Er(p.element,"ytp-videowall-still-round-medium",E>96&&E<256);g.Er(p.element,"ytp-videowall-still-round-small",E<=96);F=O[F];p.suggestion!==F&&(p.suggestion=F,E=p.api.D(),u=g.fU(p.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",gS(p,F,u),g.DY(E)&&!p.api.j("web_player_log_click_before_generating_ve_conversion_params")&&(E=F.S5(),u={},g.a9(p.api,"addEmbedsConversionTrackingParams",
[u]),E=g.bd(E,u),p.updateValue("url",E)),(F=(F=F.sessionData)&&F.itct)&&p.api.setTrackingParams(p.element,F));V++}H.ariaBusy="false";g.Er(this.element,"ytp-endscreen-paginate",V<r);for(O=this.stills.length-1;O>=V;O--)l=this.stills[O],g.Cg(l.element),g.gs(l);this.stills.length=V}};
g.C.onVideoDataChange=function(){var l=this.player.getVideoData(1);this.videoData!==l&&(l!=null&&g.Ce(l)?(this.N=0,this.videoData=l,this.Sp()):this.player.AC("missg",{vid:(l==null?void 0:l.videoId)||"",cpn:(l==null?void 0:l.clientPlaybackNonce)||""}))};
g.C.yd=function(){this.N+=this.stills.length;this.Sp()};
g.C.by=function(){this.N-=this.stills.length;this.Sp()};
g.C.NL=function(){return this.G.qV()};
g.C.Zz=function(l){l===1?(this.L=!1,this.B=this.videoData.clientPlaybackNonce,this.G.dE(),this.OF&&this.Sp()):(this.L=!0,this.OF&&KB(this)&&(l===2?this.G.Qa():l===3&&this.G.CM()))};
g.C.OJ=function(l){if(l){for(l=0;l<this.stills.length;l++)this.V.logVisibility(this.stills[l].element,!0);this.Zz(1)}else this.B=null,this.L=!1;this.Sp()};
g.C.TA=function(){return this.OF&&KB(this)};g.M(Yp,SQ);Yp.prototype.hasSuggestions=function(){var l;return(l=this.G)==null?void 0:l.hasSuggestions()};
Yp.prototype.show=function(){if(this.player.getPlayerState()!==3){SQ.prototype.show.call(this);var l=this.K;if(l){var y=this.G.hasSuggestions();g.Er(this.element,"ytp-shorts-branded-ui",y);y?l.show():l.hide()}var r;(r=g.qE(this.player))==null||r.oR(!0);this.player.logVisibility(this.element,!0);this.watchButton.JD(!0)}};
Yp.prototype.hide=function(){SQ.prototype.hide.call(this);var l;(l=g.qE(this.player))==null||l.oR(!1);this.player.logVisibility(this.element,!1);this.watchButton.JD(!1)};g.M(Hns,g.IG);g.C=Hns.prototype;g.C.Ci=function(){var l=this.player.getVideoData(),y=l.mutedAutoplay&&(l.limitedPlaybackDurationInSeconds>0||l.endSeconds>0||l.mutedAutoplayDurationMode!==2);if((this.player.isEmbedsShortsMode()||this.K)&&!y)return!0;var r;var c=!!((l==null?0:g.Ce(l))||(l==null?0:(r=l.suggestions)==null?0:r.length));c=!rvQ(this.player)||c;l=l.X7;r=this.player.f2();return c&&!l&&!r&&!y};
g.C.TA=function(){return this.endScreen.TA()};
g.C.nN7=function(){return this.TA()?this.endScreen.NL():!1};
g.C.yr=function(){this.player.sX("endscreen");g.IG.prototype.yr.call(this)};
g.C.load=function(){var l=this.player.getVideoData();var y=l.transitionEndpointAtEndOfStream;if(y&&y.videoId){var r=this.player.bT().YZ.get("heartbeat"),c=g.Ce(l);!c||y.videoId!==c.videoId||l.Qy?(this.player.FS(y.videoId,void 0,void 0,!0,!0,y),r&&r.N0("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),l=!0):l=!1}else l=!1;l||(g.IG.prototype.load.call(this),this.endScreen.show())};
g.C.unload=function(){g.IG.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.C.onCueRangeEnter=function(l){this.Ci()&&(this.endScreen.created||this.endScreen.create(),l.getId()==="load"&&this.load())};
g.C.onCueRangeExit=function(l){l.getId()==="load"&&this.loaded&&this.unload()};
g.C.onVideoDataChange=function(){Onp(this);this.B&&cvQ(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.G?this.endScreen=new pB(this.player):this.endScreen=new sW(this.player),g.Q(this,this.endScreen),g.wQ(this.player,this.endScreen.element,4))};g.K8("endscreen",Hns);})(_yt_player);
